# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_layout.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PhylogeneticVisualization(object):
    def setupUi(self, PhylogeneticVisualization):
        PhylogeneticVisualization.setObjectName(_fromUtf8("PhylogeneticVisualization"))
        PhylogeneticVisualization.resize(777, 1001)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PhylogeneticVisualization.sizePolicy().hasHeightForWidth())
        PhylogeneticVisualization.setSizePolicy(sizePolicy)
        PhylogeneticVisualization.setMinimumSize(QtCore.QSize(459, 245))
        self.centralwidget = QtGui.QWidget(PhylogeneticVisualization)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.inputMainHorizontalLayout = QtGui.QHBoxLayout()
        self.inputMainHorizontalLayout.setObjectName(_fromUtf8("inputMainHorizontalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.welcomePage = QtGui.QWidget()
        self.welcomePage.setObjectName(_fromUtf8("welcomePage"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.welcomePage)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.welcomeLabel = QtGui.QLabel(self.welcomePage)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setObjectName(_fromUtf8("welcomeLabel"))
        self.horizontalLayout_8.addWidget(self.welcomeLabel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.modeComboBox = QtGui.QComboBox(self.welcomePage)
        self.modeComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.modeComboBox.setObjectName(_fromUtf8("modeComboBox"))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.modeComboBox)
        self.launchBtn = QtGui.QPushButton(self.welcomePage)
        self.launchBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.launchBtn.setObjectName(_fromUtf8("launchBtn"))
        self.verticalLayout_4.addWidget(self.launchBtn)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.welcomeLogoImage = QtGui.QLabel(self.welcomePage)
        self.welcomeLogoImage.setText(_fromUtf8(""))
        self.welcomeLogoImage.setObjectName(_fromUtf8("welcomeLogoImage"))
        self.horizontalLayout_4.addWidget(self.welcomeLogoImage)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.welcomePage)
        self.inputPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputPage.sizePolicy().hasHeightForWidth())
        self.inputPage.setSizePolicy(sizePolicy)
        self.inputPage.setMinimumSize(QtCore.QSize(435, 488))
        self.inputPage.setBaseSize(QtCore.QSize(0, 0))
        self.inputPage.setObjectName(_fromUtf8("inputPage"))
        self.verticalLayout = QtGui.QVBoxLayout(self.inputPage)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.inputFileBtn = QtGui.QPushButton(self.inputPage)
        self.inputFileBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.inputFileBtn.setObjectName(_fromUtf8("inputFileBtn"))
        self.horizontalLayout_6.addWidget(self.inputFileBtn)
        self.inputFileEntry = QtGui.QLineEdit(self.inputPage)
        self.inputFileEntry.setMinimumSize(QtCore.QSize(0, 21))
        self.inputFileEntry.setMouseTracking(True)
        self.inputFileEntry.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.inputFileEntry.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.inputFileEntry.setObjectName(_fromUtf8("inputFileEntry"))
        self.horizontalLayout_6.addWidget(self.inputFileEntry)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.toolBox = QtGui.QToolBox(self.inputPage)
        self.toolBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setAutoFillBackground(True)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_4 = QtGui.QWidget()
        self.page_4.setEnabled(True)
        self.page_4.setGeometry(QtCore.QRect(0, 0, 727, 703))
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_21.setMargin(0)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.groupBox_2 = QtGui.QGroupBox(self.page_4)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_75 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_75.setObjectName(_fromUtf8("horizontalLayout_75"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_76 = QtGui.QHBoxLayout()
        self.horizontalLayout_76.setObjectName(_fromUtf8("horizontalLayout_76"))
        self.checkboxAllBootstrap_2 = QtGui.QCheckBox(self.groupBox_2)
        self.checkboxAllBootstrap_2.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxAllBootstrap_2.setFont(font)
        self.checkboxAllBootstrap_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkboxAllBootstrap_2.setChecked(True)
        self.checkboxAllBootstrap_2.setObjectName(_fromUtf8("checkboxAllBootstrap_2"))
        self.horizontalLayout_76.addWidget(self.checkboxAllBootstrap_2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_76.addItem(spacerItem6)
        self.verticalLayout_16.addLayout(self.horizontalLayout_76)
        self.grouopie_2 = QtGui.QGroupBox(self.groupBox_2)
        self.grouopie_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grouopie_2.setObjectName(_fromUtf8("grouopie_2"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.grouopie_2)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.label_6 = QtGui.QLabel(self.grouopie_2)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_22.addWidget(self.label_6)
        self.lineEdit_3 = QtGui.QLineEdit(self.grouopie_2)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.verticalLayout_22.addWidget(self.lineEdit_3)
        self.label_7 = QtGui.QLabel(self.grouopie_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_22.addWidget(self.label_7)
        self.lineEdit_4 = QtGui.QLineEdit(self.grouopie_2)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.verticalLayout_22.addWidget(self.lineEdit_4)
        self.verticalLayout_16.addWidget(self.grouopie_2)
        self.horizontalLayout_75.addLayout(self.verticalLayout_16)
        self.line_7 = QtGui.QFrame(self.groupBox_2)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.horizontalLayout_75.addWidget(self.line_7)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.horizontalLayout_83 = QtGui.QHBoxLayout()
        self.horizontalLayout_83.setObjectName(_fromUtf8("horizontalLayout_83"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_83.addItem(spacerItem7)
        self.windowSizeLabel_9 = QtGui.QLabel(self.groupBox_2)
        self.windowSizeLabel_9.setObjectName(_fromUtf8("windowSizeLabel_9"))
        self.horizontalLayout_83.addWidget(self.windowSizeLabel_9)
        self.windowSizeEntry_9 = QtGui.QLineEdit(self.groupBox_2)
        self.windowSizeEntry_9.setMinimumSize(QtCore.QSize(40, 21))
        self.windowSizeEntry_9.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.windowSizeEntry_9.setFont(font)
        self.windowSizeEntry_9.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.windowSizeEntry_9.setObjectName(_fromUtf8("windowSizeEntry_9"))
        self.horizontalLayout_83.addWidget(self.windowSizeEntry_9)
        self.verticalLayout_23.addLayout(self.horizontalLayout_83)
        self.horizontalLayout_84 = QtGui.QHBoxLayout()
        self.horizontalLayout_84.setObjectName(_fromUtf8("horizontalLayout_84"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_84.addItem(spacerItem8)
        self.windowOffsetLabel_9 = QtGui.QLabel(self.groupBox_2)
        self.windowOffsetLabel_9.setObjectName(_fromUtf8("windowOffsetLabel_9"))
        self.horizontalLayout_84.addWidget(self.windowOffsetLabel_9)
        self.windowOffsetEntry_9 = QtGui.QLineEdit(self.groupBox_2)
        self.windowOffsetEntry_9.setMinimumSize(QtCore.QSize(40, 21))
        self.windowOffsetEntry_9.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.windowOffsetEntry_9.setFont(font)
        self.windowOffsetEntry_9.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.windowOffsetEntry_9.setObjectName(_fromUtf8("windowOffsetEntry_9"))
        self.horizontalLayout_84.addWidget(self.windowOffsetEntry_9)
        self.verticalLayout_23.addLayout(self.horizontalLayout_84)
        self.horizontalLayout_85 = QtGui.QHBoxLayout()
        self.horizontalLayout_85.setObjectName(_fromUtf8("horizontalLayout_85"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_85.addItem(spacerItem9)
        self.numberOfTopTopologiesLabel_9 = QtGui.QLabel(self.groupBox_2)
        self.numberOfTopTopologiesLabel_9.setObjectName(_fromUtf8("numberOfTopTopologiesLabel_9"))
        self.horizontalLayout_85.addWidget(self.numberOfTopTopologiesLabel_9)
        self.numberOfTopTopologiesEntry_9 = QtGui.QLineEdit(self.groupBox_2)
        self.numberOfTopTopologiesEntry_9.setMinimumSize(QtCore.QSize(40, 21))
        self.numberOfTopTopologiesEntry_9.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.numberOfTopTopologiesEntry_9.setFont(font)
        self.numberOfTopTopologiesEntry_9.setObjectName(_fromUtf8("numberOfTopTopologiesEntry_9"))
        self.horizontalLayout_85.addWidget(self.numberOfTopTopologiesEntry_9)
        self.verticalLayout_23.addLayout(self.horizontalLayout_85)
        self.horizontalLayout_75.addLayout(self.verticalLayout_23)
        self.verticalLayout_21.addWidget(self.groupBox_2)
        self.toolBox.addItem(self.page_4, _fromUtf8(""))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 278, 157))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.groupBox_4 = QtGui.QGroupBox(self.page_5)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.checkboxAllTrees_3 = QtGui.QCheckBox(self.groupBox_4)
        self.checkboxAllTrees_3.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxAllTrees_3.setFont(font)
        self.checkboxAllTrees_3.setChecked(True)
        self.checkboxAllTrees_3.setObjectName(_fromUtf8("checkboxAllTrees_3"))
        self.horizontalLayout_31.addWidget(self.checkboxAllTrees_3)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem10)
        self.verticalLayout_10.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.checkboxScatterPlot_3 = QtGui.QCheckBox(self.groupBox_4)
        self.checkboxScatterPlot_3.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxScatterPlot_3.setFont(font)
        self.checkboxScatterPlot_3.setChecked(True)
        self.checkboxScatterPlot_3.setObjectName(_fromUtf8("checkboxScatterPlot_3"))
        self.horizontalLayout_32.addWidget(self.checkboxScatterPlot_3)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem11)
        self.verticalLayout_10.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.checkboxDonutPlot_3 = QtGui.QCheckBox(self.groupBox_4)
        self.checkboxDonutPlot_3.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxDonutPlot_3.setFont(font)
        self.checkboxDonutPlot_3.setChecked(True)
        self.checkboxDonutPlot_3.setObjectName(_fromUtf8("checkboxDonutPlot_3"))
        self.horizontalLayout_33.addWidget(self.checkboxDonutPlot_3)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem12)
        self.verticalLayout_10.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_30.addLayout(self.verticalLayout_10)
        self.line_4 = QtGui.QFrame(self.groupBox_4)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_30.addWidget(self.line_4)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.checkboxStatistics_3 = QtGui.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxStatistics_3.setFont(font)
        self.checkboxStatistics_3.setChecked(False)
        self.checkboxStatistics_3.setObjectName(_fromUtf8("checkboxStatistics_3"))
        self.horizontalLayout_9.addWidget(self.checkboxStatistics_3)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        self.checkboxCircleGraph_3 = QtGui.QCheckBox(self.groupBox_4)
        self.checkboxCircleGraph_3.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxCircleGraph_3.setFont(font)
        self.checkboxCircleGraph_3.setChecked(True)
        self.checkboxCircleGraph_3.setObjectName(_fromUtf8("checkboxCircleGraph_3"))
        self.horizontalLayout_34.addWidget(self.checkboxCircleGraph_3)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem14)
        self.verticalLayout_11.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.checkboxHeatMap_3 = QtGui.QCheckBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxHeatMap_3.setFont(font)
        self.checkboxHeatMap_3.setChecked(True)
        self.checkboxHeatMap_3.setObjectName(_fromUtf8("checkboxHeatMap_3"))
        self.horizontalLayout_35.addWidget(self.checkboxHeatMap_3)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem15)
        self.verticalLayout_11.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_30.addLayout(self.verticalLayout_11)
        self.verticalLayout_9.addWidget(self.groupBox_4)
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setEnabled(True)
        self.page_6.setGeometry(QtCore.QRect(0, 0, 489, 242))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.page_6)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.statisticsOptionsGroupBox_2 = QtGui.QGroupBox(self.page_6)
        self.statisticsOptionsGroupBox_2.setEnabled(True)
        self.statisticsOptionsGroupBox_2.setAutoFillBackground(False)
        self.statisticsOptionsGroupBox_2.setTitle(_fromUtf8(""))
        self.statisticsOptionsGroupBox_2.setFlat(False)
        self.statisticsOptionsGroupBox_2.setCheckable(False)
        self.statisticsOptionsGroupBox_2.setObjectName(_fromUtf8("statisticsOptionsGroupBox_2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.statisticsOptionsGroupBox_2)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.statisticsOptionsLabel_2 = QtGui.QLabel(self.statisticsOptionsGroupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statisticsOptionsLabel_2.sizePolicy().hasHeightForWidth())
        self.statisticsOptionsLabel_2.setSizePolicy(sizePolicy)
        self.statisticsOptionsLabel_2.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.statisticsOptionsLabel_2.setFont(font)
        self.statisticsOptionsLabel_2.setObjectName(_fromUtf8("statisticsOptionsLabel_2"))
        self.verticalLayout_12.addWidget(self.statisticsOptionsLabel_2)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.newickFileBtn_2 = QtGui.QPushButton(self.statisticsOptionsGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.newickFileBtn_2.setFont(font)
        self.newickFileBtn_2.setObjectName(_fromUtf8("newickFileBtn_2"))
        self.horizontalLayout_14.addWidget(self.newickFileBtn_2)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.newickFileEntry_2 = QtGui.QLineEdit(self.statisticsOptionsGroupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newickFileEntry_2.sizePolicy().hasHeightForWidth())
        self.newickFileEntry_2.setSizePolicy(sizePolicy)
        self.newickFileEntry_2.setMinimumSize(QtCore.QSize(250, 0))
        self.newickFileEntry_2.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.newickFileEntry_2.setFont(font)
        self.newickFileEntry_2.setObjectName(_fromUtf8("newickFileEntry_2"))
        self.horizontalLayout_14.addWidget(self.newickFileEntry_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.speciesTreeNewickStringsLabel_2 = QtGui.QLabel(self.statisticsOptionsGroupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speciesTreeNewickStringsLabel_2.sizePolicy().hasHeightForWidth())
        self.speciesTreeNewickStringsLabel_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.speciesTreeNewickStringsLabel_2.setFont(font)
        self.speciesTreeNewickStringsLabel_2.setObjectName(_fromUtf8("speciesTreeNewickStringsLabel_2"))
        self.horizontalLayout_15.addWidget(self.speciesTreeNewickStringsLabel_2)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem17)
        self.speciesTreeNewickStringsEntry_2 = QtGui.QLineEdit(self.statisticsOptionsGroupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speciesTreeNewickStringsEntry_2.sizePolicy().hasHeightForWidth())
        self.speciesTreeNewickStringsEntry_2.setSizePolicy(sizePolicy)
        self.speciesTreeNewickStringsEntry_2.setMinimumSize(QtCore.QSize(250, 21))
        self.speciesTreeNewickStringsEntry_2.setMaximumSize(QtCore.QSize(260, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.speciesTreeNewickStringsEntry_2.setFont(font)
        self.speciesTreeNewickStringsEntry_2.setObjectName(_fromUtf8("speciesTreeNewickStringsEntry_2"))
        self.horizontalLayout_15.addWidget(self.speciesTreeNewickStringsEntry_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.checkboxRobinsonFoulds_2 = QtGui.QCheckBox(self.statisticsOptionsGroupBox_2)
        self.checkboxRobinsonFoulds_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxRobinsonFoulds_2.setFont(font)
        self.checkboxRobinsonFoulds_2.setObjectName(_fromUtf8("checkboxRobinsonFoulds_2"))
        self.horizontalLayout_16.addWidget(self.checkboxRobinsonFoulds_2)
        self.checkboxWeighted_2 = QtGui.QCheckBox(self.statisticsOptionsGroupBox_2)
        self.checkboxWeighted_2.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxWeighted_2.setFont(font)
        self.checkboxWeighted_2.setObjectName(_fromUtf8("checkboxWeighted_2"))
        self.horizontalLayout_16.addWidget(self.checkboxWeighted_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.checkboxPGTST_2 = QtGui.QCheckBox(self.statisticsOptionsGroupBox_2)
        self.checkboxPGTST_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxPGTST_2.setFont(font)
        self.checkboxPGTST_2.setObjectName(_fromUtf8("checkboxPGTST_2"))
        self.horizontalLayout_21.addWidget(self.checkboxPGTST_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.checkboxRooted_2 = QtGui.QCheckBox(self.statisticsOptionsGroupBox_2)
        self.checkboxRooted_2.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxRooted_2.setFont(font)
        self.checkboxRooted_2.setObjectName(_fromUtf8("checkboxRooted_2"))
        self.horizontalLayout_36.addWidget(self.checkboxRooted_2)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem18)
        self.outgroupLabel_2 = QtGui.QLabel(self.statisticsOptionsGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.outgroupLabel_2.setFont(font)
        self.outgroupLabel_2.setObjectName(_fromUtf8("outgroupLabel_2"))
        self.horizontalLayout_36.addWidget(self.outgroupLabel_2)
        self.outgroupEntry_2 = QtGui.QLineEdit(self.statisticsOptionsGroupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outgroupEntry_2.sizePolicy().hasHeightForWidth())
        self.outgroupEntry_2.setSizePolicy(sizePolicy)
        self.outgroupEntry_2.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.outgroupEntry_2.setFont(font)
        self.outgroupEntry_2.setObjectName(_fromUtf8("outgroupEntry_2"))
        self.horizontalLayout_36.addWidget(self.outgroupEntry_2)
        self.verticalLayout_12.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_5.addWidget(self.statisticsOptionsGroupBox_2)
        self.toolBox.addItem(self.page_6, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolBox)
        self.stackedWidget.addWidget(self.inputPage)
        self.inputPageNotRaxA = QtGui.QWidget()
        self.inputPageNotRaxA.setObjectName(_fromUtf8("inputPageNotRaxA"))
        self.gridLayout_2 = QtGui.QGridLayout(self.inputPageNotRaxA)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.inputPageNotRaxA)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.inputFormatLabel = QtGui.QLabel(self.inputPageNotRaxA)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.inputFormatLabel.setFont(font)
        self.inputFormatLabel.setObjectName(_fromUtf8("inputFormatLabel"))
        self.gridLayout_2.addWidget(self.inputFormatLabel, 3, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.inputPageNotRaxA)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 5, 0, 1, 1)
        self.outputFormatDescriptionLabel = QtGui.QLabel(self.inputPageNotRaxA)
        font = QtGui.QFont()
        font.setItalic(True)
        self.outputFormatDescriptionLabel.setFont(font)
        self.outputFormatDescriptionLabel.setObjectName(_fromUtf8("outputFormatDescriptionLabel"))
        self.gridLayout_2.addWidget(self.outputFormatDescriptionLabel, 7, 0, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem19, 8, 0, 1, 1)
        self.runFileConverterBtn = QtGui.QPushButton(self.inputPageNotRaxA)
        self.runFileConverterBtn.setObjectName(_fromUtf8("runFileConverterBtn"))
        self.gridLayout_2.addWidget(self.runFileConverterBtn, 9, 0, 1, 1)
        self.outputFormatLabel = QtGui.QLabel(self.inputPageNotRaxA)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.outputFormatLabel.setFont(font)
        self.outputFormatLabel.setObjectName(_fromUtf8("outputFormatLabel"))
        self.gridLayout_2.addWidget(self.outputFormatLabel, 6, 0, 1, 1)
        self.inputFormatComboBox = QtGui.QComboBox(self.inputPageNotRaxA)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputFormatComboBox.sizePolicy().hasHeightForWidth())
        self.inputFormatComboBox.setSizePolicy(sizePolicy)
        self.inputFormatComboBox.setObjectName(_fromUtf8("inputFormatComboBox"))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.inputFormatComboBox, 4, 0, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.fileConverterBtn = QtGui.QPushButton(self.inputPageNotRaxA)
        self.fileConverterBtn.setObjectName(_fromUtf8("fileConverterBtn"))
        self.horizontalLayout_23.addWidget(self.fileConverterBtn)
        self.fileConverterEntry = QtGui.QLineEdit(self.inputPageNotRaxA)
        self.fileConverterEntry.setObjectName(_fromUtf8("fileConverterEntry"))
        self.horizontalLayout_23.addWidget(self.fileConverterEntry)
        self.gridLayout_2.addLayout(self.horizontalLayout_23, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.inputPageNotRaxA)
        self.inputPageNotRaxB = QtGui.QWidget()
        self.inputPageNotRaxB.setObjectName(_fromUtf8("inputPageNotRaxB"))
        self.label_2 = QtGui.QLabel(self.inputPageNotRaxB)
        self.label_2.setGeometry(QtCore.QRect(180, 70, 56, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.stackedWidget.addWidget(self.inputPageNotRaxB)
        self.inputPageNotRaxC = QtGui.QWidget()
        self.inputPageNotRaxC.setObjectName(_fromUtf8("inputPageNotRaxC"))
        self.label_3 = QtGui.QLabel(self.inputPageNotRaxC)
        self.label_3.setGeometry(QtCore.QRect(180, 70, 56, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.stackedWidget.addWidget(self.inputPageNotRaxC)
        self.outputPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputPage.sizePolicy().hasHeightForWidth())
        self.outputPage.setSizePolicy(sizePolicy)
        self.outputPage.setObjectName(_fromUtf8("outputPage"))
        self.gridLayout_5 = QtGui.QGridLayout(self.outputPage)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.outputTabs = QtGui.QTabWidget(self.outputPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputTabs.sizePolicy().hasHeightForWidth())
        self.outputTabs.setSizePolicy(sizePolicy)
        self.outputTabs.setObjectName(_fromUtf8("outputTabs"))
        self.standard = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.standard.sizePolicy().hasHeightForWidth())
        self.standard.setSizePolicy(sizePolicy)
        self.standard.setObjectName(_fromUtf8("standard"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.standard)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem20)
        self.standardImage = QtGui.QLabel(self.standard)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.standardImage.sizePolicy().hasHeightForWidth())
        self.standardImage.setSizePolicy(sizePolicy)
        self.standardImage.setText(_fromUtf8(""))
        self.standardImage.setObjectName(_fromUtf8("standardImage"))
        self.horizontalLayout_3.addWidget(self.standardImage)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem21)
        self.outputTabs.addTab(self.standard, _fromUtf8(""))
        self.bootstrap = QtGui.QWidget()
        self.bootstrap.setObjectName(_fromUtf8("bootstrap"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.bootstrap)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem22)
        self.bootstrapImage = QtGui.QLabel(self.bootstrap)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bootstrapImage.sizePolicy().hasHeightForWidth())
        self.bootstrapImage.setSizePolicy(sizePolicy)
        self.bootstrapImage.setText(_fromUtf8(""))
        self.bootstrapImage.setObjectName(_fromUtf8("bootstrapImage"))
        self.horizontalLayout_2.addWidget(self.bootstrapImage)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem23)
        self.outputTabs.addTab(self.bootstrap, _fromUtf8(""))
        self.summary = QtGui.QWidget()
        self.summary.setObjectName(_fromUtf8("summary"))
        self.gridLayout_3 = QtGui.QGridLayout(self.summary)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_2 = QtGui.QPushButton(self.summary)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.outputTabs.addTab(self.summary, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.outputTabs, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.outputPage)
        self.inputMainHorizontalLayout.addWidget(self.stackedWidget)
        self.gridLayout.addLayout(self.inputMainHorizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.runBtn = QtGui.QPushButton(self.centralwidget)
        self.runBtn.setMinimumSize(QtCore.QSize(143, 0))
        self.runBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.runBtn.setObjectName(_fromUtf8("runBtn"))
        self.horizontalLayout_10.addWidget(self.runBtn)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_10.addWidget(self.progressBar)
        self.gridLayout.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_37.addWidget(self.pushButton)
        self.progressBar_2 = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.horizontalLayout_37.addWidget(self.progressBar_2)
        self.gridLayout.addLayout(self.horizontalLayout_37, 2, 0, 1, 1)
        PhylogeneticVisualization.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PhylogeneticVisualization)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExport = QtGui.QMenu(self.menuFile)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuMode = QtGui.QMenu(self.menubar)
        self.menuMode.setObjectName(_fromUtf8("menuMode"))
        self.menuDisplay = QtGui.QMenu(self.menubar)
        self.menuDisplay.setObjectName(_fromUtf8("menuDisplay"))
        PhylogeneticVisualization.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(PhylogeneticVisualization)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionRax = QtGui.QAction(PhylogeneticVisualization)
        self.actionRax.setCheckable(True)
        self.actionRax.setChecked(False)
        self.actionRax.setObjectName(_fromUtf8("actionRax"))
        self.actionConverter = QtGui.QAction(PhylogeneticVisualization)
        self.actionConverter.setCheckable(True)
        self.actionConverter.setObjectName(_fromUtf8("actionConverter"))
        self.actionNotRaxB = QtGui.QAction(PhylogeneticVisualization)
        self.actionNotRaxB.setCheckable(True)
        self.actionNotRaxB.setObjectName(_fromUtf8("actionNotRaxB"))
        self.actionNotRaxC = QtGui.QAction(PhylogeneticVisualization)
        self.actionNotRaxC.setCheckable(True)
        self.actionNotRaxC.setObjectName(_fromUtf8("actionNotRaxC"))
        self.actionStandardJPG = QtGui.QAction(PhylogeneticVisualization)
        self.actionStandardJPG.setObjectName(_fromUtf8("actionStandardJPG"))
        self.actionBootstrapJPG = QtGui.QAction(PhylogeneticVisualization)
        self.actionBootstrapJPG.setObjectName(_fromUtf8("actionBootstrapJPG"))
        self.actionTextFile = QtGui.QAction(PhylogeneticVisualization)
        self.actionTextFile.setObjectName(_fromUtf8("actionTextFile"))
        self.actionWindowsDirectory = QtGui.QAction(PhylogeneticVisualization)
        self.actionWindowsDirectory.setObjectName(_fromUtf8("actionWindowsDirectory"))
        self.actionRAXDirectory = QtGui.QAction(PhylogeneticVisualization)
        self.actionRAXDirectory.setObjectName(_fromUtf8("actionRAXDirectory"))
        self.actionTreesDirectory = QtGui.QAction(PhylogeneticVisualization)
        self.actionTreesDirectory.setObjectName(_fromUtf8("actionTreesDirectory"))
        self.actionAllTrees = QtGui.QAction(PhylogeneticVisualization)
        self.actionAllTrees.setCheckable(True)
        self.actionAllTrees.setObjectName(_fromUtf8("actionAllTrees"))
        self.actionScatterPlot = QtGui.QAction(PhylogeneticVisualization)
        self.actionScatterPlot.setCheckable(True)
        self.actionScatterPlot.setObjectName(_fromUtf8("actionScatterPlot"))
        self.actionDonutPlot = QtGui.QAction(PhylogeneticVisualization)
        self.actionDonutPlot.setCheckable(True)
        self.actionDonutPlot.setObjectName(_fromUtf8("actionDonutPlot"))
        self.actionCircleGraph = QtGui.QAction(PhylogeneticVisualization)
        self.actionCircleGraph.setCheckable(True)
        self.actionCircleGraph.setObjectName(_fromUtf8("actionCircleGraph"))
        self.actionStatistics = QtGui.QAction(PhylogeneticVisualization)
        self.actionStatistics.setObjectName(_fromUtf8("actionStatistics"))
        self.menuExport.addAction(self.actionStandardJPG)
        self.menuExport.addAction(self.actionBootstrapJPG)
        self.menuExport.addAction(self.actionTextFile)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.actionWindowsDirectory)
        self.menuExport.addAction(self.actionRAXDirectory)
        self.menuExport.addAction(self.actionTreesDirectory)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuMode.addAction(self.actionRax)
        self.menuMode.addAction(self.actionConverter)
        self.menuMode.addAction(self.actionNotRaxB)
        self.menuMode.addAction(self.actionNotRaxC)
        self.menuDisplay.addAction(self.actionAllTrees)
        self.menuDisplay.addAction(self.actionScatterPlot)
        self.menuDisplay.addAction(self.actionDonutPlot)
        self.menuDisplay.addAction(self.actionCircleGraph)
        self.menuDisplay.addAction(self.actionStatistics)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())

        self.retranslateUi(PhylogeneticVisualization)
        self.stackedWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        self.outputTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PhylogeneticVisualization)
        PhylogeneticVisualization.setTabOrder(self.outputTabs, self.pushButton_2)

    def retranslateUi(self, PhylogeneticVisualization):
        PhylogeneticVisualization.setWindowTitle(_translate("PhylogeneticVisualization", "Phylogenetic Visualization", None))
        self.welcomeLabel.setText(_translate("PhylogeneticVisualization", "Welcome Daddy", None))
        self.modeComboBox.setItemText(0, _translate("PhylogeneticVisualization", "RAx_ML", None))
        self.modeComboBox.setItemText(1, _translate("PhylogeneticVisualization", "File Converter", None))
        self.modeComboBox.setItemText(2, _translate("PhylogeneticVisualization", "not rax B", None))
        self.modeComboBox.setItemText(3, _translate("PhylogeneticVisualization", "not rax C", None))
        self.modeComboBox.setItemText(4, _translate("PhylogeneticVisualization", "Tetris", None))
        self.modeComboBox.setItemText(5, _translate("PhylogeneticVisualization", "Snake", None))
        self.launchBtn.setText(_translate("PhylogeneticVisualization", "Launch", None))
        self.inputFileBtn.setText(_translate("PhylogeneticVisualization", "Select Input File", None))
        self.inputFileEntry.setText(_translate("PhylogeneticVisualization", "/Users/Peter/PycharmProjects/Evolutionary-Diversity-Visualization-Python/testFiles/phylip.txt", None))
        self.checkboxAllBootstrap_2.setText(_translate("PhylogeneticVisualization", "Bootstrap", None))
        self.label_6.setText(_translate("PhylogeneticVisualization", "Confidence Level:", None))
        self.label_7.setText(_translate("PhylogeneticVisualization", "Number of Bootstraps:", None))
        self.windowSizeLabel_9.setText(_translate("PhylogeneticVisualization", "Window Size:", None))
        self.windowSizeEntry_9.setText(_translate("PhylogeneticVisualization", "10", None))
        self.windowOffsetLabel_9.setText(_translate("PhylogeneticVisualization", "Window Offset:", None))
        self.windowOffsetEntry_9.setText(_translate("PhylogeneticVisualization", "10", None))
        self.numberOfTopTopologiesLabel_9.setText(_translate("PhylogeneticVisualization", "Number of Top Topologies:", None))
        self.numberOfTopTopologiesEntry_9.setText(_translate("PhylogeneticVisualization", "5", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("PhylogeneticVisualization", "RAxML Options", None))
        self.checkboxAllTrees_3.setText(_translate("PhylogeneticVisualization", "All Trees", None))
        self.checkboxScatterPlot_3.setText(_translate("PhylogeneticVisualization", "Scatter Plot", None))
        self.checkboxDonutPlot_3.setText(_translate("PhylogeneticVisualization", "Donut Plot", None))
        self.checkboxStatistics_3.setText(_translate("PhylogeneticVisualization", "Statistics", None))
        self.checkboxCircleGraph_3.setText(_translate("PhylogeneticVisualization", "Circle Graph", None))
        self.checkboxHeatMap_3.setText(_translate("PhylogeneticVisualization", "Heat Map", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("PhylogeneticVisualization", "Graph Options", None))
        self.statisticsOptionsLabel_2.setText(_translate("PhylogeneticVisualization", "Statistics Options", None))
        self.newickFileBtn_2.setText(_translate("PhylogeneticVisualization", "Select Newick File", None))
        self.newickFileEntry_2.setText(_translate("PhylogeneticVisualization", "/Users/Peter/PycharmProjects/Evolutionary-Diversity-Visualization-Python/RAx_Files/RAxML_bestTree.0", None))
        self.speciesTreeNewickStringsLabel_2.setText(_translate("PhylogeneticVisualization", "Species Tree Newick String:", None))
        self.checkboxRobinsonFoulds_2.setText(_translate("PhylogeneticVisualization", "Robinson Foulds", None))
        self.checkboxWeighted_2.setText(_translate("PhylogeneticVisualization", "Weighted", None))
        self.checkboxPGTST_2.setText(_translate("PhylogeneticVisualization", "p(GT | ST)", None))
        self.checkboxRooted_2.setText(_translate("PhylogeneticVisualization", "rooted", None))
        self.outgroupLabel_2.setText(_translate("PhylogeneticVisualization", "Outgroup:", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("PhylogeneticVisualization", "Statistics Options", None))
        self.label.setText(_translate("PhylogeneticVisualization", "Input File", None))
        self.inputFormatLabel.setText(_translate("PhylogeneticVisualization", "Input Format:", None))
        self.outputFormatDescriptionLabel.setText(_translate("PhylogeneticVisualization", "This is a relaxed interpretation of the PHYLIP format which allows\n"
" long names.", None))
        self.runFileConverterBtn.setText(_translate("PhylogeneticVisualization", "Convert", None))
        self.outputFormatLabel.setText(_translate("PhylogeneticVisualization", "Output Format:", None))
        self.inputFormatComboBox.setItemText(0, _translate("PhylogeneticVisualization", "CLUSTAL", None))
        self.inputFormatComboBox.setItemText(1, _translate("PhylogeneticVisualization", "EMBOSS", None))
        self.inputFormatComboBox.setItemText(2, _translate("PhylogeneticVisualization", "FASTA", None))
        self.inputFormatComboBox.setItemText(3, _translate("PhylogeneticVisualization", "FASTA-m10", None))
        self.inputFormatComboBox.setItemText(4, _translate("PhylogeneticVisualization", "IG", None))
        self.inputFormatComboBox.setItemText(5, _translate("PhylogeneticVisualization", "MAF", None))
        self.inputFormatComboBox.setItemText(6, _translate("PhylogeneticVisualization", "Mauve", None))
        self.inputFormatComboBox.setItemText(7, _translate("PhylogeneticVisualization", "NEXUS", None))
        self.inputFormatComboBox.setItemText(8, _translate("PhylogeneticVisualization", "PHYLIP", None))
        self.inputFormatComboBox.setItemText(9, _translate("PhylogeneticVisualization", "PHYLIP-sequential", None))
        self.inputFormatComboBox.setItemText(10, _translate("PhylogeneticVisualization", "Stockholm", None))
        self.fileConverterBtn.setText(_translate("PhylogeneticVisualization", "Choose File", None))
        self.label_2.setText(_translate("PhylogeneticVisualization", "notRaxB", None))
        self.label_3.setText(_translate("PhylogeneticVisualization", "notRaxC", None))
        self.outputTabs.setTabText(self.outputTabs.indexOf(self.standard), _translate("PhylogeneticVisualization", "Standard", None))
        self.outputTabs.setTabText(self.outputTabs.indexOf(self.bootstrap), _translate("PhylogeneticVisualization", "Boostrap", None))
        self.pushButton_2.setText(_translate("PhylogeneticVisualization", "PushButton", None))
        self.outputTabs.setTabText(self.outputTabs.indexOf(self.summary), _translate("PhylogeneticVisualization", "Summary", None))
        self.runBtn.setText(_translate("PhylogeneticVisualization", "Run RAxML", None))
        self.pushButton.setText(_translate("PhylogeneticVisualization", "Generate Graphs", None))
        self.menuFile.setTitle(_translate("PhylogeneticVisualization", "File", None))
        self.menuExport.setTitle(_translate("PhylogeneticVisualization", "Export...", None))
        self.menuMode.setTitle(_translate("PhylogeneticVisualization", "Mode", None))
        self.menuDisplay.setTitle(_translate("PhylogeneticVisualization", "Display", None))
        self.actionOpen.setText(_translate("PhylogeneticVisualization", "Open...", None))
        self.actionOpen.setShortcut(_translate("PhylogeneticVisualization", "Ctrl+O", None))
        self.actionRax.setText(_translate("PhylogeneticVisualization", "RAx_ML", None))
        self.actionConverter.setText(_translate("PhylogeneticVisualization", "Converter", None))
        self.actionNotRaxB.setText(_translate("PhylogeneticVisualization", "Not Rax B", None))
        self.actionNotRaxC.setText(_translate("PhylogeneticVisualization", "Not Rax C", None))
        self.actionStandardJPG.setText(_translate("PhylogeneticVisualization", "Standard JPG", None))
        self.actionBootstrapJPG.setText(_translate("PhylogeneticVisualization", "Bootstrap JPG ", None))
        self.actionTextFile.setText(_translate("PhylogeneticVisualization", "Text File", None))
        self.actionWindowsDirectory.setText(_translate("PhylogeneticVisualization", "Windows Directory", None))
        self.actionRAXDirectory.setText(_translate("PhylogeneticVisualization", "RAX Directory", None))
        self.actionTreesDirectory.setText(_translate("PhylogeneticVisualization", "Trees Directory", None))
        self.actionAllTrees.setText(_translate("PhylogeneticVisualization", "All Trees", None))
        self.actionScatterPlot.setText(_translate("PhylogeneticVisualization", "Scatter Plot", None))
        self.actionDonutPlot.setText(_translate("PhylogeneticVisualization", "Donut Plot", None))
        self.actionCircleGraph.setText(_translate("PhylogeneticVisualization", "Circle Graph", None))
        self.actionStatistics.setText(_translate("PhylogeneticVisualization", "Statistics", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    PhylogeneticVisualization = QtGui.QMainWindow()
    ui = Ui_PhylogeneticVisualization()
    ui.setupUi(PhylogeneticVisualization)
    PhylogeneticVisualization.show()
    sys.exit(app.exec_())

