# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_layout.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PhylogeneticVisualization(object):
    def setupUi(self, PhylogeneticVisualization):
        PhylogeneticVisualization.setObjectName(_fromUtf8("PhylogeneticVisualization"))
        PhylogeneticVisualization.resize(777, 1001)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PhylogeneticVisualization.sizePolicy().hasHeightForWidth())
        PhylogeneticVisualization.setSizePolicy(sizePolicy)
        PhylogeneticVisualization.setMinimumSize(QtCore.QSize(459, 245))
        self.centralwidget = QtGui.QWidget(PhylogeneticVisualization)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.inputMainHorizontalLayout = QtGui.QHBoxLayout()
        self.inputMainHorizontalLayout.setObjectName(_fromUtf8("inputMainHorizontalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.welcomePage = QtGui.QWidget()
        self.welcomePage.setObjectName(_fromUtf8("welcomePage"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.welcomePage)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.welcomeLabel = QtGui.QLabel(self.welcomePage)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setObjectName(_fromUtf8("welcomeLabel"))
        self.horizontalLayout_8.addWidget(self.welcomeLabel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.modeComboBox = QtGui.QComboBox(self.welcomePage)
        self.modeComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.modeComboBox.setObjectName(_fromUtf8("modeComboBox"))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.modeComboBox)
        self.launchBtn = QtGui.QPushButton(self.welcomePage)
        self.launchBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.launchBtn.setObjectName(_fromUtf8("launchBtn"))
        self.verticalLayout_4.addWidget(self.launchBtn)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.welcomeLogoImage = QtGui.QLabel(self.welcomePage)
        self.welcomeLogoImage.setText(_fromUtf8(""))
        self.welcomeLogoImage.setObjectName(_fromUtf8("welcomeLogoImage"))
        self.horizontalLayout_4.addWidget(self.welcomeLogoImage)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.welcomePage)
        self.inputPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputPage.sizePolicy().hasHeightForWidth())
        self.inputPage.setSizePolicy(sizePolicy)
        self.inputPage.setMinimumSize(QtCore.QSize(435, 488))
        self.inputPage.setBaseSize(QtCore.QSize(0, 0))
        self.inputPage.setObjectName(_fromUtf8("inputPage"))
        self.verticalLayout = QtGui.QVBoxLayout(self.inputPage)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.inputFileHL = QtGui.QHBoxLayout()
        self.inputFileHL.setObjectName(_fromUtf8("inputFileHL"))
        self.inputFileLabel = QtGui.QLabel(self.inputPage)
        self.inputFileLabel.setObjectName(_fromUtf8("inputFileLabel"))
        self.inputFileHL.addWidget(self.inputFileLabel)
        self.inputFileEntry = QtGui.QLineEdit(self.inputPage)
        self.inputFileEntry.setMinimumSize(QtCore.QSize(0, 21))
        self.inputFileEntry.setMouseTracking(True)
        self.inputFileEntry.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.inputFileEntry.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.inputFileEntry.setObjectName(_fromUtf8("inputFileEntry"))
        self.inputFileHL.addWidget(self.inputFileEntry)
        self.inputFileBtn = QtGui.QToolButton(self.inputPage)
        self.inputFileBtn.setObjectName(_fromUtf8("inputFileBtn"))
        self.inputFileHL.addWidget(self.inputFileBtn)
        self.verticalLayout.addLayout(self.inputFileHL)
        self.raxmlToolBox = QtGui.QToolBox(self.inputPage)
        self.raxmlToolBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raxmlToolBox.sizePolicy().hasHeightForWidth())
        self.raxmlToolBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.raxmlToolBox.setFont(font)
        self.raxmlToolBox.setAutoFillBackground(True)
        self.raxmlToolBox.setObjectName(_fromUtf8("raxmlToolBox"))
        self.raxmlOptionsPage = QtGui.QWidget()
        self.raxmlOptionsPage.setEnabled(True)
        self.raxmlOptionsPage.setGeometry(QtCore.QRect(0, 0, 727, 713))
        self.raxmlOptionsPage.setObjectName(_fromUtf8("raxmlOptionsPage"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.raxmlOptionsPage)
        self.verticalLayout_21.setMargin(0)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.raxmlOptionsTabWidget = QtGui.QTabWidget(self.raxmlOptionsPage)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.raxmlOptionsTabWidget.setFont(font)
        self.raxmlOptionsTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.raxmlOptionsTabWidget.setUsesScrollButtons(False)
        self.raxmlOptionsTabWidget.setDocumentMode(False)
        self.raxmlOptionsTabWidget.setObjectName(_fromUtf8("raxmlOptionsTabWidget"))
        self.raxmlStandardOptionsTab = QtGui.QWidget()
        self.raxmlStandardOptionsTab.setObjectName(_fromUtf8("raxmlStandardOptionsTab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.raxmlStandardOptionsTab)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.bootstrapHL = QtGui.QHBoxLayout()
        self.bootstrapHL.setObjectName(_fromUtf8("bootstrapHL"))
        self.checkboxBootstrap = QtGui.QCheckBox(self.raxmlStandardOptionsTab)
        self.checkboxBootstrap.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxBootstrap.setFont(font)
        self.checkboxBootstrap.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkboxBootstrap.setChecked(False)
        self.checkboxBootstrap.setObjectName(_fromUtf8("checkboxBootstrap"))
        self.bootstrapHL.addWidget(self.checkboxBootstrap)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bootstrapHL.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.bootstrapHL)
        self.bootstrapGroupBox = QtGui.QGroupBox(self.raxmlStandardOptionsTab)
        self.bootstrapGroupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bootstrapGroupBox.setObjectName(_fromUtf8("bootstrapGroupBox"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.bootstrapGroupBox)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.confidenceLevelLabel = QtGui.QLabel(self.bootstrapGroupBox)
        self.confidenceLevelLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.confidenceLevelLabel.setObjectName(_fromUtf8("confidenceLevelLabel"))
        self.verticalLayout_24.addWidget(self.confidenceLevelLabel)
        self.confidenceLevelEntry = QtGui.QLineEdit(self.bootstrapGroupBox)
        self.confidenceLevelEntry.setMinimumSize(QtCore.QSize(40, 0))
        self.confidenceLevelEntry.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.confidenceLevelEntry.setFont(font)
        self.confidenceLevelEntry.setText(_fromUtf8(""))
        self.confidenceLevelEntry.setObjectName(_fromUtf8("confidenceLevelEntry"))
        self.verticalLayout_24.addWidget(self.confidenceLevelEntry)
        self.numberOfBootstrapsLabel = QtGui.QLabel(self.bootstrapGroupBox)
        self.numberOfBootstrapsLabel.setObjectName(_fromUtf8("numberOfBootstrapsLabel"))
        self.verticalLayout_24.addWidget(self.numberOfBootstrapsLabel)
        self.numberOfBootstrapsEntry = QtGui.QLineEdit(self.bootstrapGroupBox)
        self.numberOfBootstrapsEntry.setMinimumSize(QtCore.QSize(40, 0))
        self.numberOfBootstrapsEntry.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.numberOfBootstrapsEntry.setFont(font)
        self.numberOfBootstrapsEntry.setObjectName(_fromUtf8("numberOfBootstrapsEntry"))
        self.verticalLayout_24.addWidget(self.numberOfBootstrapsEntry)
        self.verticalLayout_2.addWidget(self.bootstrapGroupBox)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.raxmlOptionsVLine = QtGui.QFrame(self.raxmlStandardOptionsTab)
        self.raxmlOptionsVLine.setFrameShape(QtGui.QFrame.VLine)
        self.raxmlOptionsVLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.raxmlOptionsVLine.setObjectName(_fromUtf8("raxmlOptionsVLine"))
        self.horizontalLayout.addWidget(self.raxmlOptionsVLine)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.windowSizeHL = QtGui.QHBoxLayout()
        self.windowSizeHL.setObjectName(_fromUtf8("windowSizeHL"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.windowSizeHL.addItem(spacerItem8)
        self.windowSizeLabel = QtGui.QLabel(self.raxmlStandardOptionsTab)
        self.windowSizeLabel.setObjectName(_fromUtf8("windowSizeLabel"))
        self.windowSizeHL.addWidget(self.windowSizeLabel)
        self.windowSizeEntry = QtGui.QLineEdit(self.raxmlStandardOptionsTab)
        self.windowSizeEntry.setMinimumSize(QtCore.QSize(40, 21))
        self.windowSizeEntry.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.windowSizeEntry.setFont(font)
        self.windowSizeEntry.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.windowSizeEntry.setObjectName(_fromUtf8("windowSizeEntry"))
        self.windowSizeHL.addWidget(self.windowSizeEntry)
        self.verticalLayout_25.addLayout(self.windowSizeHL)
        self.windowOffsetHL = QtGui.QHBoxLayout()
        self.windowOffsetHL.setObjectName(_fromUtf8("windowOffsetHL"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.windowOffsetHL.addItem(spacerItem9)
        self.windowOffsetLabel = QtGui.QLabel(self.raxmlStandardOptionsTab)
        self.windowOffsetLabel.setObjectName(_fromUtf8("windowOffsetLabel"))
        self.windowOffsetHL.addWidget(self.windowOffsetLabel)
        self.windowOffsetEntry = QtGui.QLineEdit(self.raxmlStandardOptionsTab)
        self.windowOffsetEntry.setMinimumSize(QtCore.QSize(40, 21))
        self.windowOffsetEntry.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.windowOffsetEntry.setFont(font)
        self.windowOffsetEntry.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.windowOffsetEntry.setObjectName(_fromUtf8("windowOffsetEntry"))
        self.windowOffsetHL.addWidget(self.windowOffsetEntry)
        self.verticalLayout_25.addLayout(self.windowOffsetHL)
        self.numberOfTopTopologiesHL = QtGui.QHBoxLayout()
        self.numberOfTopTopologiesHL.setObjectName(_fromUtf8("numberOfTopTopologiesHL"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.numberOfTopTopologiesHL.addItem(spacerItem10)
        self.numberOfTopTopologiesLabel = QtGui.QLabel(self.raxmlStandardOptionsTab)
        self.numberOfTopTopologiesLabel.setObjectName(_fromUtf8("numberOfTopTopologiesLabel"))
        self.numberOfTopTopologiesHL.addWidget(self.numberOfTopTopologiesLabel)
        self.numberOfTopTopologiesEntry = QtGui.QLineEdit(self.raxmlStandardOptionsTab)
        self.numberOfTopTopologiesEntry.setMinimumSize(QtCore.QSize(40, 21))
        self.numberOfTopTopologiesEntry.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.numberOfTopTopologiesEntry.setFont(font)
        self.numberOfTopTopologiesEntry.setObjectName(_fromUtf8("numberOfTopTopologiesEntry"))
        self.numberOfTopTopologiesHL.addWidget(self.numberOfTopTopologiesEntry)
        self.verticalLayout_25.addLayout(self.numberOfTopTopologiesHL)
        self.horizontalLayout.addLayout(self.verticalLayout_25)
        self.raxmlOptionsTabWidget.addTab(self.raxmlStandardOptionsTab, _fromUtf8(""))
        self.raxmlAdvancedOptionsTab = QtGui.QWidget()
        self.raxmlAdvancedOptionsTab.setObjectName(_fromUtf8("raxmlAdvancedOptionsTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.raxmlAdvancedOptionsTab)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_4 = QtGui.QLabel(self.raxmlAdvancedOptionsTab)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_9.addWidget(self.label_4)
        self.checkBox = QtGui.QCheckBox(self.raxmlAdvancedOptionsTab)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_9.addWidget(self.checkBox)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.lineEdit = QtGui.QLineEdit(self.raxmlAdvancedOptionsTab)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_3.addWidget(self.lineEdit)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem12)
        self.label_5 = QtGui.QLabel(self.raxmlAdvancedOptionsTab)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.raxmlAdvancedOptionsTab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lineEdit_2 = QtGui.QLineEdit(self.raxmlAdvancedOptionsTab)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_7.addWidget(self.lineEdit_2)
        self.toolButton = QtGui.QToolButton(self.raxmlAdvancedOptionsTab)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_7.addWidget(self.toolButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem13)
        self.label_7 = QtGui.QLabel(self.raxmlAdvancedOptionsTab)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.raxmlAdvancedOptionsTab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lineEdit_3 = QtGui.QLineEdit(self.raxmlAdvancedOptionsTab)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        self.toolButton_2 = QtGui.QToolButton(self.raxmlAdvancedOptionsTab)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.horizontalLayout_6.addWidget(self.toolButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem14)
        self.label_9 = QtGui.QLabel(self.raxmlAdvancedOptionsTab)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.runRaxmlHL_2 = QtGui.QHBoxLayout()
        self.runRaxmlHL_2.setObjectName(_fromUtf8("runRaxmlHL_2"))
        self.runBtn_2 = QtGui.QPushButton(self.raxmlAdvancedOptionsTab)
        self.runBtn_2.setMinimumSize(QtCore.QSize(143, 0))
        self.runBtn_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.runBtn_2.setObjectName(_fromUtf8("runBtn_2"))
        self.runRaxmlHL_2.addWidget(self.runBtn_2)
        self.progressBar_2 = QtGui.QProgressBar(self.raxmlAdvancedOptionsTab)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.runRaxmlHL_2.addWidget(self.progressBar_2)
        self.verticalLayout_3.addLayout(self.runRaxmlHL_2)
        self.raxmlOptionsTabWidget.addTab(self.raxmlAdvancedOptionsTab, _fromUtf8(""))
        self.verticalLayout_21.addWidget(self.raxmlOptionsTabWidget)
        self.raxmlToolBox.addItem(self.raxmlOptionsPage, _fromUtf8(""))
        self.graphOptionsPage = QtGui.QWidget()
        self.graphOptionsPage.setGeometry(QtCore.QRect(0, 0, 727, 713))
        self.graphOptionsPage.setObjectName(_fromUtf8("graphOptionsPage"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.graphOptionsPage)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.graphOptionsGroupBox = QtGui.QGroupBox(self.graphOptionsPage)
        self.graphOptionsGroupBox.setObjectName(_fromUtf8("graphOptionsGroupBox"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.graphOptionsGroupBox)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.allTreesHL = QtGui.QHBoxLayout()
        self.allTreesHL.setObjectName(_fromUtf8("allTreesHL"))
        self.checkboxAllTrees = QtGui.QCheckBox(self.graphOptionsGroupBox)
        self.checkboxAllTrees.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxAllTrees.setFont(font)
        self.checkboxAllTrees.setChecked(True)
        self.checkboxAllTrees.setObjectName(_fromUtf8("checkboxAllTrees"))
        self.allTreesHL.addWidget(self.checkboxAllTrees)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.allTreesHL.addItem(spacerItem15)
        self.verticalLayout_10.addLayout(self.allTreesHL)
        self.scatterPlotHL = QtGui.QHBoxLayout()
        self.scatterPlotHL.setObjectName(_fromUtf8("scatterPlotHL"))
        self.checkboxScatterPlot = QtGui.QCheckBox(self.graphOptionsGroupBox)
        self.checkboxScatterPlot.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxScatterPlot.setFont(font)
        self.checkboxScatterPlot.setChecked(True)
        self.checkboxScatterPlot.setObjectName(_fromUtf8("checkboxScatterPlot"))
        self.scatterPlotHL.addWidget(self.checkboxScatterPlot)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.scatterPlotHL.addItem(spacerItem16)
        self.verticalLayout_10.addLayout(self.scatterPlotHL)
        self.scatterPlotHL_2 = QtGui.QHBoxLayout()
        self.scatterPlotHL_2.setObjectName(_fromUtf8("scatterPlotHL_2"))
        self.checkboxDonutPlot = QtGui.QCheckBox(self.graphOptionsGroupBox)
        self.checkboxDonutPlot.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxDonutPlot.setFont(font)
        self.checkboxDonutPlot.setChecked(True)
        self.checkboxDonutPlot.setObjectName(_fromUtf8("checkboxDonutPlot"))
        self.scatterPlotHL_2.addWidget(self.checkboxDonutPlot)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.scatterPlotHL_2.addItem(spacerItem17)
        self.verticalLayout_10.addLayout(self.scatterPlotHL_2)
        self.horizontalLayout_30.addLayout(self.verticalLayout_10)
        self.graphOptionsVLine = QtGui.QFrame(self.graphOptionsGroupBox)
        self.graphOptionsVLine.setFrameShape(QtGui.QFrame.VLine)
        self.graphOptionsVLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.graphOptionsVLine.setObjectName(_fromUtf8("graphOptionsVLine"))
        self.horizontalLayout_30.addWidget(self.graphOptionsVLine)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.statisticsHL = QtGui.QHBoxLayout()
        self.statisticsHL.setObjectName(_fromUtf8("statisticsHL"))
        self.checkboxStatistics = QtGui.QCheckBox(self.graphOptionsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxStatistics.setFont(font)
        self.checkboxStatistics.setChecked(False)
        self.checkboxStatistics.setObjectName(_fromUtf8("checkboxStatistics"))
        self.statisticsHL.addWidget(self.checkboxStatistics)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.statisticsHL.addItem(spacerItem18)
        self.verticalLayout_11.addLayout(self.statisticsHL)
        self.circleGraphHL = QtGui.QHBoxLayout()
        self.circleGraphHL.setObjectName(_fromUtf8("circleGraphHL"))
        self.checkboxCircleGraph = QtGui.QCheckBox(self.graphOptionsGroupBox)
        self.checkboxCircleGraph.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxCircleGraph.setFont(font)
        self.checkboxCircleGraph.setChecked(True)
        self.checkboxCircleGraph.setObjectName(_fromUtf8("checkboxCircleGraph"))
        self.circleGraphHL.addWidget(self.checkboxCircleGraph)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.circleGraphHL.addItem(spacerItem19)
        self.verticalLayout_11.addLayout(self.circleGraphHL)
        self.heatMapHL = QtGui.QHBoxLayout()
        self.heatMapHL.setObjectName(_fromUtf8("heatMapHL"))
        self.checkboxHeatMap = QtGui.QCheckBox(self.graphOptionsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxHeatMap.setFont(font)
        self.checkboxHeatMap.setChecked(True)
        self.checkboxHeatMap.setObjectName(_fromUtf8("checkboxHeatMap"))
        self.heatMapHL.addWidget(self.checkboxHeatMap)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.heatMapHL.addItem(spacerItem20)
        self.verticalLayout_11.addLayout(self.heatMapHL)
        self.horizontalLayout_30.addLayout(self.verticalLayout_11)
        self.verticalLayout_9.addWidget(self.graphOptionsGroupBox)
        self.raxmlToolBox.addItem(self.graphOptionsPage, _fromUtf8(""))
        self.statisticsOptionsPage = QtGui.QWidget()
        self.statisticsOptionsPage.setEnabled(True)
        self.statisticsOptionsPage.setGeometry(QtCore.QRect(0, 0, 727, 713))
        self.statisticsOptionsPage.setObjectName(_fromUtf8("statisticsOptionsPage"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.statisticsOptionsPage)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.statisticsOptionsGroupBox = QtGui.QGroupBox(self.statisticsOptionsPage)
        self.statisticsOptionsGroupBox.setEnabled(True)
        self.statisticsOptionsGroupBox.setAutoFillBackground(False)
        self.statisticsOptionsGroupBox.setTitle(_fromUtf8(""))
        self.statisticsOptionsGroupBox.setFlat(False)
        self.statisticsOptionsGroupBox.setCheckable(False)
        self.statisticsOptionsGroupBox.setObjectName(_fromUtf8("statisticsOptionsGroupBox"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.statisticsOptionsGroupBox)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.newickFileHL = QtGui.QHBoxLayout()
        self.newickFileHL.setObjectName(_fromUtf8("newickFileHL"))
        self.newickFileBtn = QtGui.QPushButton(self.statisticsOptionsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.newickFileBtn.setFont(font)
        self.newickFileBtn.setObjectName(_fromUtf8("newickFileBtn"))
        self.newickFileHL.addWidget(self.newickFileBtn)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.newickFileHL.addItem(spacerItem21)
        self.newickFileEntry = QtGui.QLineEdit(self.statisticsOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newickFileEntry.sizePolicy().hasHeightForWidth())
        self.newickFileEntry.setSizePolicy(sizePolicy)
        self.newickFileEntry.setMinimumSize(QtCore.QSize(250, 0))
        self.newickFileEntry.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.newickFileEntry.setFont(font)
        self.newickFileEntry.setObjectName(_fromUtf8("newickFileEntry"))
        self.newickFileHL.addWidget(self.newickFileEntry)
        self.verticalLayout_12.addLayout(self.newickFileHL)
        self.newickStringHL = QtGui.QHBoxLayout()
        self.newickStringHL.setObjectName(_fromUtf8("newickStringHL"))
        self.speciesTreeNewickStringsLabel = QtGui.QLabel(self.statisticsOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speciesTreeNewickStringsLabel.sizePolicy().hasHeightForWidth())
        self.speciesTreeNewickStringsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.speciesTreeNewickStringsLabel.setFont(font)
        self.speciesTreeNewickStringsLabel.setObjectName(_fromUtf8("speciesTreeNewickStringsLabel"))
        self.newickStringHL.addWidget(self.speciesTreeNewickStringsLabel)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.newickStringHL.addItem(spacerItem22)
        self.speciesTreeNewickStringsEntry = QtGui.QLineEdit(self.statisticsOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speciesTreeNewickStringsEntry.sizePolicy().hasHeightForWidth())
        self.speciesTreeNewickStringsEntry.setSizePolicy(sizePolicy)
        self.speciesTreeNewickStringsEntry.setMinimumSize(QtCore.QSize(250, 21))
        self.speciesTreeNewickStringsEntry.setMaximumSize(QtCore.QSize(260, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.speciesTreeNewickStringsEntry.setFont(font)
        self.speciesTreeNewickStringsEntry.setText(_fromUtf8(""))
        self.speciesTreeNewickStringsEntry.setObjectName(_fromUtf8("speciesTreeNewickStringsEntry"))
        self.newickStringHL.addWidget(self.speciesTreeNewickStringsEntry)
        self.verticalLayout_12.addLayout(self.newickStringHL)
        self.robinsonFouldsHL = QtGui.QHBoxLayout()
        self.robinsonFouldsHL.setObjectName(_fromUtf8("robinsonFouldsHL"))
        self.checkboxRobinsonFoulds = QtGui.QCheckBox(self.statisticsOptionsGroupBox)
        self.checkboxRobinsonFoulds.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxRobinsonFoulds.setFont(font)
        self.checkboxRobinsonFoulds.setObjectName(_fromUtf8("checkboxRobinsonFoulds"))
        self.robinsonFouldsHL.addWidget(self.checkboxRobinsonFoulds)
        self.checkboxWeighted = QtGui.QCheckBox(self.statisticsOptionsGroupBox)
        self.checkboxWeighted.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxWeighted.setFont(font)
        self.checkboxWeighted.setObjectName(_fromUtf8("checkboxWeighted"))
        self.robinsonFouldsHL.addWidget(self.checkboxWeighted)
        self.verticalLayout_12.addLayout(self.robinsonFouldsHL)
        self.pgtstHL = QtGui.QHBoxLayout()
        self.pgtstHL.setObjectName(_fromUtf8("pgtstHL"))
        self.checkboxPGTST = QtGui.QCheckBox(self.statisticsOptionsGroupBox)
        self.checkboxPGTST.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxPGTST.setFont(font)
        self.checkboxPGTST.setObjectName(_fromUtf8("checkboxPGTST"))
        self.pgtstHL.addWidget(self.checkboxPGTST)
        self.verticalLayout_12.addLayout(self.pgtstHL)
        self.rootedHL = QtGui.QHBoxLayout()
        self.rootedHL.setObjectName(_fromUtf8("rootedHL"))
        self.checkboxRooted = QtGui.QCheckBox(self.statisticsOptionsGroupBox)
        self.checkboxRooted.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxRooted.setFont(font)
        self.checkboxRooted.setObjectName(_fromUtf8("checkboxRooted"))
        self.rootedHL.addWidget(self.checkboxRooted)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.rootedHL.addItem(spacerItem23)
        self.outgroupLabel = QtGui.QLabel(self.statisticsOptionsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.outgroupLabel.setFont(font)
        self.outgroupLabel.setObjectName(_fromUtf8("outgroupLabel"))
        self.rootedHL.addWidget(self.outgroupLabel)
        self.outgroupEntry = QtGui.QLineEdit(self.statisticsOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outgroupEntry.sizePolicy().hasHeightForWidth())
        self.outgroupEntry.setSizePolicy(sizePolicy)
        self.outgroupEntry.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.outgroupEntry.setFont(font)
        self.outgroupEntry.setText(_fromUtf8(""))
        self.outgroupEntry.setObjectName(_fromUtf8("outgroupEntry"))
        self.rootedHL.addWidget(self.outgroupEntry)
        self.verticalLayout_12.addLayout(self.rootedHL)
        self.horizontalLayout_5.addWidget(self.statisticsOptionsGroupBox)
        self.raxmlToolBox.addItem(self.statisticsOptionsPage, _fromUtf8(""))
        self.verticalLayout.addWidget(self.raxmlToolBox)
        self.runRaxmlHL = QtGui.QHBoxLayout()
        self.runRaxmlHL.setObjectName(_fromUtf8("runRaxmlHL"))
        self.runBtn = QtGui.QPushButton(self.inputPage)
        self.runBtn.setMinimumSize(QtCore.QSize(143, 0))
        self.runBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.runBtn.setObjectName(_fromUtf8("runBtn"))
        self.runRaxmlHL.addWidget(self.runBtn)
        self.progressBar = QtGui.QProgressBar(self.inputPage)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.runRaxmlHL.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.runRaxmlHL)
        self.generateGraphsHL = QtGui.QHBoxLayout()
        self.generateGraphsHL.setObjectName(_fromUtf8("generateGraphsHL"))
        self.generateGraphsBtn = QtGui.QPushButton(self.inputPage)
        self.generateGraphsBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.generateGraphsBtn.setObjectName(_fromUtf8("generateGraphsBtn"))
        self.generateGraphsHL.addWidget(self.generateGraphsBtn)
        self.generateGraphsProgressBar = QtGui.QProgressBar(self.inputPage)
        self.generateGraphsProgressBar.setProperty("value", 24)
        self.generateGraphsProgressBar.setObjectName(_fromUtf8("generateGraphsProgressBar"))
        self.generateGraphsHL.addWidget(self.generateGraphsProgressBar)
        self.verticalLayout.addLayout(self.generateGraphsHL)
        self.stackedWidget.addWidget(self.inputPage)
        self.inputPageNotRaxA = QtGui.QWidget()
        self.inputPageNotRaxA.setObjectName(_fromUtf8("inputPageNotRaxA"))
        self.gridLayout_2 = QtGui.QGridLayout(self.inputPageNotRaxA)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.inputPageNotRaxA)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.inputFormatLabel = QtGui.QLabel(self.inputPageNotRaxA)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.inputFormatLabel.setFont(font)
        self.inputFormatLabel.setObjectName(_fromUtf8("inputFormatLabel"))
        self.gridLayout_2.addWidget(self.inputFormatLabel, 3, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.inputPageNotRaxA)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 5, 0, 1, 1)
        self.outputFormatDescriptionLabel = QtGui.QLabel(self.inputPageNotRaxA)
        font = QtGui.QFont()
        font.setItalic(True)
        self.outputFormatDescriptionLabel.setFont(font)
        self.outputFormatDescriptionLabel.setObjectName(_fromUtf8("outputFormatDescriptionLabel"))
        self.gridLayout_2.addWidget(self.outputFormatDescriptionLabel, 7, 0, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem24, 8, 0, 1, 1)
        self.runFileConverterBtn = QtGui.QPushButton(self.inputPageNotRaxA)
        self.runFileConverterBtn.setObjectName(_fromUtf8("runFileConverterBtn"))
        self.gridLayout_2.addWidget(self.runFileConverterBtn, 9, 0, 1, 1)
        self.outputFormatLabel = QtGui.QLabel(self.inputPageNotRaxA)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.outputFormatLabel.setFont(font)
        self.outputFormatLabel.setObjectName(_fromUtf8("outputFormatLabel"))
        self.gridLayout_2.addWidget(self.outputFormatLabel, 6, 0, 1, 1)
        self.inputFormatComboBox = QtGui.QComboBox(self.inputPageNotRaxA)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputFormatComboBox.sizePolicy().hasHeightForWidth())
        self.inputFormatComboBox.setSizePolicy(sizePolicy)
        self.inputFormatComboBox.setObjectName(_fromUtf8("inputFormatComboBox"))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.inputFormatComboBox, 4, 0, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.fileConverterBtn = QtGui.QPushButton(self.inputPageNotRaxA)
        self.fileConverterBtn.setObjectName(_fromUtf8("fileConverterBtn"))
        self.horizontalLayout_23.addWidget(self.fileConverterBtn)
        self.fileConverterEntry = QtGui.QLineEdit(self.inputPageNotRaxA)
        self.fileConverterEntry.setObjectName(_fromUtf8("fileConverterEntry"))
        self.horizontalLayout_23.addWidget(self.fileConverterEntry)
        self.gridLayout_2.addLayout(self.horizontalLayout_23, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.inputPageNotRaxA)
        self.inputPageNotRaxB = QtGui.QWidget()
        self.inputPageNotRaxB.setObjectName(_fromUtf8("inputPageNotRaxB"))
        self.label_2 = QtGui.QLabel(self.inputPageNotRaxB)
        self.label_2.setGeometry(QtCore.QRect(180, 70, 56, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.stackedWidget.addWidget(self.inputPageNotRaxB)
        self.inputPageNotRaxC = QtGui.QWidget()
        self.inputPageNotRaxC.setObjectName(_fromUtf8("inputPageNotRaxC"))
        self.label_3 = QtGui.QLabel(self.inputPageNotRaxC)
        self.label_3.setGeometry(QtCore.QRect(180, 70, 56, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.stackedWidget.addWidget(self.inputPageNotRaxC)
        self.outputPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputPage.sizePolicy().hasHeightForWidth())
        self.outputPage.setSizePolicy(sizePolicy)
        self.outputPage.setObjectName(_fromUtf8("outputPage"))
        self.gridLayout_5 = QtGui.QGridLayout(self.outputPage)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.outputTabs = QtGui.QTabWidget(self.outputPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputTabs.sizePolicy().hasHeightForWidth())
        self.outputTabs.setSizePolicy(sizePolicy)
        self.outputTabs.setObjectName(_fromUtf8("outputTabs"))
        self.standard = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.standard.sizePolicy().hasHeightForWidth())
        self.standard.setSizePolicy(sizePolicy)
        self.standard.setObjectName(_fromUtf8("standard"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.standard)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem25)
        self.standardImage = QtGui.QLabel(self.standard)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.standardImage.sizePolicy().hasHeightForWidth())
        self.standardImage.setSizePolicy(sizePolicy)
        self.standardImage.setText(_fromUtf8(""))
        self.standardImage.setObjectName(_fromUtf8("standardImage"))
        self.horizontalLayout_3.addWidget(self.standardImage)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem26)
        self.outputTabs.addTab(self.standard, _fromUtf8(""))
        self.bootstrap = QtGui.QWidget()
        self.bootstrap.setObjectName(_fromUtf8("bootstrap"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.bootstrap)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem27)
        self.bootstrapImage = QtGui.QLabel(self.bootstrap)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bootstrapImage.sizePolicy().hasHeightForWidth())
        self.bootstrapImage.setSizePolicy(sizePolicy)
        self.bootstrapImage.setText(_fromUtf8(""))
        self.bootstrapImage.setObjectName(_fromUtf8("bootstrapImage"))
        self.horizontalLayout_2.addWidget(self.bootstrapImage)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem28)
        self.outputTabs.addTab(self.bootstrap, _fromUtf8(""))
        self.summary = QtGui.QWidget()
        self.summary.setObjectName(_fromUtf8("summary"))
        self.gridLayout_3 = QtGui.QGridLayout(self.summary)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_2 = QtGui.QPushButton(self.summary)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.outputTabs.addTab(self.summary, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.outputTabs, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.outputPage)
        self.inputMainHorizontalLayout.addWidget(self.stackedWidget)
        self.gridLayout.addLayout(self.inputMainHorizontalLayout, 0, 0, 1, 1)
        PhylogeneticVisualization.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PhylogeneticVisualization)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExport = QtGui.QMenu(self.menuFile)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuMode = QtGui.QMenu(self.menubar)
        self.menuMode.setObjectName(_fromUtf8("menuMode"))
        self.menuDisplay = QtGui.QMenu(self.menubar)
        self.menuDisplay.setObjectName(_fromUtf8("menuDisplay"))
        PhylogeneticVisualization.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(PhylogeneticVisualization)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionRax = QtGui.QAction(PhylogeneticVisualization)
        self.actionRax.setCheckable(True)
        self.actionRax.setChecked(False)
        self.actionRax.setObjectName(_fromUtf8("actionRax"))
        self.actionConverter = QtGui.QAction(PhylogeneticVisualization)
        self.actionConverter.setCheckable(True)
        self.actionConverter.setObjectName(_fromUtf8("actionConverter"))
        self.actionNotRaxB = QtGui.QAction(PhylogeneticVisualization)
        self.actionNotRaxB.setCheckable(True)
        self.actionNotRaxB.setObjectName(_fromUtf8("actionNotRaxB"))
        self.actionNotRaxC = QtGui.QAction(PhylogeneticVisualization)
        self.actionNotRaxC.setCheckable(True)
        self.actionNotRaxC.setObjectName(_fromUtf8("actionNotRaxC"))
        self.actionStandardJPG = QtGui.QAction(PhylogeneticVisualization)
        self.actionStandardJPG.setObjectName(_fromUtf8("actionStandardJPG"))
        self.actionBootstrapJPG = QtGui.QAction(PhylogeneticVisualization)
        self.actionBootstrapJPG.setObjectName(_fromUtf8("actionBootstrapJPG"))
        self.actionTextFile = QtGui.QAction(PhylogeneticVisualization)
        self.actionTextFile.setObjectName(_fromUtf8("actionTextFile"))
        self.actionWindowsDirectory = QtGui.QAction(PhylogeneticVisualization)
        self.actionWindowsDirectory.setObjectName(_fromUtf8("actionWindowsDirectory"))
        self.actionRAXDirectory = QtGui.QAction(PhylogeneticVisualization)
        self.actionRAXDirectory.setObjectName(_fromUtf8("actionRAXDirectory"))
        self.actionTreesDirectory = QtGui.QAction(PhylogeneticVisualization)
        self.actionTreesDirectory.setObjectName(_fromUtf8("actionTreesDirectory"))
        self.actionAllTrees = QtGui.QAction(PhylogeneticVisualization)
        self.actionAllTrees.setCheckable(True)
        self.actionAllTrees.setObjectName(_fromUtf8("actionAllTrees"))
        self.actionScatterPlot = QtGui.QAction(PhylogeneticVisualization)
        self.actionScatterPlot.setCheckable(True)
        self.actionScatterPlot.setObjectName(_fromUtf8("actionScatterPlot"))
        self.actionDonutPlot = QtGui.QAction(PhylogeneticVisualization)
        self.actionDonutPlot.setCheckable(True)
        self.actionDonutPlot.setObjectName(_fromUtf8("actionDonutPlot"))
        self.actionCircleGraph = QtGui.QAction(PhylogeneticVisualization)
        self.actionCircleGraph.setCheckable(True)
        self.actionCircleGraph.setObjectName(_fromUtf8("actionCircleGraph"))
        self.actionStatistics = QtGui.QAction(PhylogeneticVisualization)
        self.actionStatistics.setObjectName(_fromUtf8("actionStatistics"))
        self.menuExport.addAction(self.actionStandardJPG)
        self.menuExport.addAction(self.actionBootstrapJPG)
        self.menuExport.addAction(self.actionTextFile)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.actionWindowsDirectory)
        self.menuExport.addAction(self.actionRAXDirectory)
        self.menuExport.addAction(self.actionTreesDirectory)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuMode.addAction(self.actionRax)
        self.menuMode.addAction(self.actionConverter)
        self.menuMode.addAction(self.actionNotRaxB)
        self.menuMode.addAction(self.actionNotRaxC)
        self.menuDisplay.addAction(self.actionAllTrees)
        self.menuDisplay.addAction(self.actionScatterPlot)
        self.menuDisplay.addAction(self.actionDonutPlot)
        self.menuDisplay.addAction(self.actionCircleGraph)
        self.menuDisplay.addAction(self.actionStatistics)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())

        self.retranslateUi(PhylogeneticVisualization)
        self.stackedWidget.setCurrentIndex(1)
        self.raxmlToolBox.setCurrentIndex(0)
        self.raxmlOptionsTabWidget.setCurrentIndex(1)
        self.outputTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PhylogeneticVisualization)
        PhylogeneticVisualization.setTabOrder(self.outputTabs, self.pushButton_2)

    def retranslateUi(self, PhylogeneticVisualization):
        PhylogeneticVisualization.setWindowTitle(_translate("PhylogeneticVisualization", "Phylogenetic Visualization", None))
        self.welcomeLabel.setText(_translate("PhylogeneticVisualization", "Welcome Daddy", None))
        self.modeComboBox.setItemText(0, _translate("PhylogeneticVisualization", "RAx_ML", None))
        self.modeComboBox.setItemText(1, _translate("PhylogeneticVisualization", "File Converter", None))
        self.modeComboBox.setItemText(2, _translate("PhylogeneticVisualization", "not rax B", None))
        self.modeComboBox.setItemText(3, _translate("PhylogeneticVisualization", "not rax C", None))
        self.modeComboBox.setItemText(4, _translate("PhylogeneticVisualization", "Tetris", None))
        self.modeComboBox.setItemText(5, _translate("PhylogeneticVisualization", "Snake", None))
        self.launchBtn.setText(_translate("PhylogeneticVisualization", "Launch", None))
        self.inputFileLabel.setText(_translate("PhylogeneticVisualization", "Input File:", None))
        self.inputFileEntry.setText(_translate("PhylogeneticVisualization", "/Users/Peter/PycharmProjects/Evolutionary-Diversity-Visualization-Python/testFiles/phylip.txt", None))
        self.inputFileBtn.setText(_translate("PhylogeneticVisualization", "...", None))
        self.checkboxBootstrap.setText(_translate("PhylogeneticVisualization", "Bootstrap", None))
        self.confidenceLevelLabel.setText(_translate("PhylogeneticVisualization", "Confidence Level:", None))
        self.numberOfBootstrapsLabel.setText(_translate("PhylogeneticVisualization", "Number of Bootstraps:", None))
        self.windowSizeLabel.setText(_translate("PhylogeneticVisualization", "Window Size:", None))
        self.windowSizeEntry.setText(_translate("PhylogeneticVisualization", "10", None))
        self.windowOffsetLabel.setText(_translate("PhylogeneticVisualization", "Window Offset:", None))
        self.windowOffsetEntry.setText(_translate("PhylogeneticVisualization", "10", None))
        self.numberOfTopTopologiesLabel.setText(_translate("PhylogeneticVisualization", "Number of Top Topologies:", None))
        self.numberOfTopTopologiesEntry.setText(_translate("PhylogeneticVisualization", "5", None))
        self.raxmlOptionsTabWidget.setTabText(self.raxmlOptionsTabWidget.indexOf(self.raxmlStandardOptionsTab), _translate("PhylogeneticVisualization", "Standard", None))
        self.label_4.setText(_translate("PhylogeneticVisualization", "Custom RAxML Command", None))
        self.label_5.setText(_translate("PhylogeneticVisualization", "Custom Alignment Windows Directory", None))
        self.label_6.setText(_translate("PhylogeneticVisualization", "If you have already run RAxML select the alignment directory below.", None))
        self.toolButton.setText(_translate("PhylogeneticVisualization", "...", None))
        self.label_7.setText(_translate("PhylogeneticVisualization", "Custom RAxML Directory", None))
        self.label_8.setText(_translate("PhylogeneticVisualization", "If you have already run RAxML select the alignment directory below.", None))
        self.toolButton_2.setText(_translate("PhylogeneticVisualization", "...", None))
        self.label_9.setText(_translate("PhylogeneticVisualization", "Generate Species Tree", None))
        self.runBtn_2.setText(_translate("PhylogeneticVisualization", "Run RAxML", None))
        self.raxmlOptionsTabWidget.setTabText(self.raxmlOptionsTabWidget.indexOf(self.raxmlAdvancedOptionsTab), _translate("PhylogeneticVisualization", "Advanced", None))
        self.raxmlToolBox.setItemText(self.raxmlToolBox.indexOf(self.raxmlOptionsPage), _translate("PhylogeneticVisualization", "RAxML Options", None))
        self.checkboxAllTrees.setText(_translate("PhylogeneticVisualization", "All Trees", None))
        self.checkboxScatterPlot.setText(_translate("PhylogeneticVisualization", "Scatter Plot", None))
        self.checkboxDonutPlot.setText(_translate("PhylogeneticVisualization", "Donut Plot", None))
        self.checkboxStatistics.setText(_translate("PhylogeneticVisualization", "Statistics", None))
        self.checkboxCircleGraph.setText(_translate("PhylogeneticVisualization", "Circle Graph", None))
        self.checkboxHeatMap.setText(_translate("PhylogeneticVisualization", "Heat Map", None))
        self.raxmlToolBox.setItemText(self.raxmlToolBox.indexOf(self.graphOptionsPage), _translate("PhylogeneticVisualization", "Graph Options", None))
        self.newickFileBtn.setText(_translate("PhylogeneticVisualization", "Select Newick File", None))
        self.newickFileEntry.setText(_translate("PhylogeneticVisualization", "/Users/Peter/PycharmProjects/Evolutionary-Diversity-Visualization-Python/RAx_Files/RAxML_bestTree.0", None))
        self.speciesTreeNewickStringsLabel.setText(_translate("PhylogeneticVisualization", "Species Tree Newick String:", None))
        self.checkboxRobinsonFoulds.setText(_translate("PhylogeneticVisualization", "Robinson Foulds", None))
        self.checkboxWeighted.setText(_translate("PhylogeneticVisualization", "Weighted", None))
        self.checkboxPGTST.setText(_translate("PhylogeneticVisualization", "p(GT | ST)", None))
        self.checkboxRooted.setText(_translate("PhylogeneticVisualization", "rooted", None))
        self.outgroupLabel.setText(_translate("PhylogeneticVisualization", "Outgroup:", None))
        self.raxmlToolBox.setItemText(self.raxmlToolBox.indexOf(self.statisticsOptionsPage), _translate("PhylogeneticVisualization", "Statistics Options", None))
        self.runBtn.setText(_translate("PhylogeneticVisualization", "Run RAxML", None))
        self.generateGraphsBtn.setText(_translate("PhylogeneticVisualization", "Generate Graphs", None))
        self.label.setText(_translate("PhylogeneticVisualization", "Input File", None))
        self.inputFormatLabel.setText(_translate("PhylogeneticVisualization", "Input Format:", None))
        self.outputFormatDescriptionLabel.setText(_translate("PhylogeneticVisualization", "This is a relaxed interpretation of the PHYLIP format which allows\n"
" long names.", None))
        self.runFileConverterBtn.setText(_translate("PhylogeneticVisualization", "Convert", None))
        self.outputFormatLabel.setText(_translate("PhylogeneticVisualization", "Output Format:", None))
        self.inputFormatComboBox.setItemText(0, _translate("PhylogeneticVisualization", "CLUSTAL", None))
        self.inputFormatComboBox.setItemText(1, _translate("PhylogeneticVisualization", "EMBOSS", None))
        self.inputFormatComboBox.setItemText(2, _translate("PhylogeneticVisualization", "FASTA", None))
        self.inputFormatComboBox.setItemText(3, _translate("PhylogeneticVisualization", "FASTA-m10", None))
        self.inputFormatComboBox.setItemText(4, _translate("PhylogeneticVisualization", "IG", None))
        self.inputFormatComboBox.setItemText(5, _translate("PhylogeneticVisualization", "MAF", None))
        self.inputFormatComboBox.setItemText(6, _translate("PhylogeneticVisualization", "Mauve", None))
        self.inputFormatComboBox.setItemText(7, _translate("PhylogeneticVisualization", "NEXUS", None))
        self.inputFormatComboBox.setItemText(8, _translate("PhylogeneticVisualization", "PHYLIP", None))
        self.inputFormatComboBox.setItemText(9, _translate("PhylogeneticVisualization", "PHYLIP-sequential", None))
        self.inputFormatComboBox.setItemText(10, _translate("PhylogeneticVisualization", "Stockholm", None))
        self.fileConverterBtn.setText(_translate("PhylogeneticVisualization", "Choose File", None))
        self.label_2.setText(_translate("PhylogeneticVisualization", "notRaxB", None))
        self.label_3.setText(_translate("PhylogeneticVisualization", "notRaxC", None))
        self.outputTabs.setTabText(self.outputTabs.indexOf(self.standard), _translate("PhylogeneticVisualization", "Standard", None))
        self.outputTabs.setTabText(self.outputTabs.indexOf(self.bootstrap), _translate("PhylogeneticVisualization", "Boostrap", None))
        self.pushButton_2.setText(_translate("PhylogeneticVisualization", "PushButton", None))
        self.outputTabs.setTabText(self.outputTabs.indexOf(self.summary), _translate("PhylogeneticVisualization", "Summary", None))
        self.menuFile.setTitle(_translate("PhylogeneticVisualization", "File", None))
        self.menuExport.setTitle(_translate("PhylogeneticVisualization", "Export...", None))
        self.menuMode.setTitle(_translate("PhylogeneticVisualization", "Mode", None))
        self.menuDisplay.setTitle(_translate("PhylogeneticVisualization", "Display", None))
        self.actionOpen.setText(_translate("PhylogeneticVisualization", "Open...", None))
        self.actionOpen.setShortcut(_translate("PhylogeneticVisualization", "Ctrl+O", None))
        self.actionRax.setText(_translate("PhylogeneticVisualization", "RAx_ML", None))
        self.actionConverter.setText(_translate("PhylogeneticVisualization", "Converter", None))
        self.actionNotRaxB.setText(_translate("PhylogeneticVisualization", "Not Rax B", None))
        self.actionNotRaxC.setText(_translate("PhylogeneticVisualization", "Not Rax C", None))
        self.actionStandardJPG.setText(_translate("PhylogeneticVisualization", "Standard JPG", None))
        self.actionBootstrapJPG.setText(_translate("PhylogeneticVisualization", "Bootstrap JPG ", None))
        self.actionTextFile.setText(_translate("PhylogeneticVisualization", "Text File", None))
        self.actionWindowsDirectory.setText(_translate("PhylogeneticVisualization", "Windows Directory", None))
        self.actionRAXDirectory.setText(_translate("PhylogeneticVisualization", "RAX Directory", None))
        self.actionTreesDirectory.setText(_translate("PhylogeneticVisualization", "Trees Directory", None))
        self.actionAllTrees.setText(_translate("PhylogeneticVisualization", "All Trees", None))
        self.actionScatterPlot.setText(_translate("PhylogeneticVisualization", "Scatter Plot", None))
        self.actionDonutPlot.setText(_translate("PhylogeneticVisualization", "Donut Plot", None))
        self.actionCircleGraph.setText(_translate("PhylogeneticVisualization", "Circle Graph", None))
        self.actionStatistics.setText(_translate("PhylogeneticVisualization", "Statistics", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    PhylogeneticVisualization = QtGui.QMainWindow()
    ui = Ui_PhylogeneticVisualization()
    ui.setupUi(PhylogeneticVisualization)
    PhylogeneticVisualization.show()
    sys.exit(app.exec_())

