# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(709, 970)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.inputFileBtn = QtGui.QPushButton(self.centralwidget)
        self.inputFileBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.inputFileBtn.setObjectName(_fromUtf8("inputFileBtn"))
        self.horizontalLayout_3.addWidget(self.inputFileBtn)
        self.inputFileEntry = QtGui.QLineEdit(self.centralwidget)
        self.inputFileEntry.setMinimumSize(QtCore.QSize(0, 21))
        self.inputFileEntry.setMouseTracking(True)
        self.inputFileEntry.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.inputFileEntry.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.inputFileEntry.setObjectName(_fromUtf8("inputFileEntry"))
        self.horizontalLayout_3.addWidget(self.inputFileEntry)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setAutoFillBackground(True)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setEnabled(True)
        self.page.setGeometry(QtCore.QRect(0, 0, 685, 698))
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_19.setMargin(0)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.groupBox = QtGui.QGroupBox(self.page)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_73 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_73.setObjectName(_fromUtf8("horizontalLayout_73"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_74 = QtGui.QHBoxLayout()
        self.horizontalLayout_74.setObjectName(_fromUtf8("horizontalLayout_74"))
        self.checkboxAllBootstrap = QtGui.QCheckBox(self.groupBox)
        self.checkboxAllBootstrap.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxAllBootstrap.setFont(font)
        self.checkboxAllBootstrap.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkboxAllBootstrap.setChecked(True)
        self.checkboxAllBootstrap.setObjectName(_fromUtf8("checkboxAllBootstrap"))
        self.horizontalLayout_74.addWidget(self.checkboxAllBootstrap)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_74.addItem(spacerItem)
        self.verticalLayout_15.addLayout(self.horizontalLayout_74)
        self.grouopie = QtGui.QGroupBox(self.groupBox)
        self.grouopie.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.grouopie.setObjectName(_fromUtf8("grouopie"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.grouopie)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.label = QtGui.QLabel(self.grouopie)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_20.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.grouopie)
        self.lineEdit.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_20.addWidget(self.lineEdit)
        self.label_2 = QtGui.QLabel(self.grouopie)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_20.addWidget(self.label_2)
        self.lineEdit_2 = QtGui.QLineEdit(self.grouopie)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(40, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_20.addWidget(self.lineEdit_2)
        self.verticalLayout_15.addWidget(self.grouopie)
        self.horizontalLayout_73.addLayout(self.verticalLayout_15)
        self.line_6 = QtGui.QFrame(self.groupBox)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout_73.addWidget(self.line_6)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_80 = QtGui.QHBoxLayout()
        self.horizontalLayout_80.setObjectName(_fromUtf8("horizontalLayout_80"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_80.addItem(spacerItem1)
        self.windowSizeLabel_8 = QtGui.QLabel(self.groupBox)
        self.windowSizeLabel_8.setObjectName(_fromUtf8("windowSizeLabel_8"))
        self.horizontalLayout_80.addWidget(self.windowSizeLabel_8)
        self.windowSizeEntry_8 = QtGui.QLineEdit(self.groupBox)
        self.windowSizeEntry_8.setMinimumSize(QtCore.QSize(40, 21))
        self.windowSizeEntry_8.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.windowSizeEntry_8.setFont(font)
        self.windowSizeEntry_8.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.windowSizeEntry_8.setObjectName(_fromUtf8("windowSizeEntry_8"))
        self.horizontalLayout_80.addWidget(self.windowSizeEntry_8)
        self.verticalLayout_18.addLayout(self.horizontalLayout_80)
        self.horizontalLayout_81 = QtGui.QHBoxLayout()
        self.horizontalLayout_81.setObjectName(_fromUtf8("horizontalLayout_81"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_81.addItem(spacerItem2)
        self.windowOffsetLabel_8 = QtGui.QLabel(self.groupBox)
        self.windowOffsetLabel_8.setObjectName(_fromUtf8("windowOffsetLabel_8"))
        self.horizontalLayout_81.addWidget(self.windowOffsetLabel_8)
        self.windowOffsetEntry_8 = QtGui.QLineEdit(self.groupBox)
        self.windowOffsetEntry_8.setMinimumSize(QtCore.QSize(40, 21))
        self.windowOffsetEntry_8.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.windowOffsetEntry_8.setFont(font)
        self.windowOffsetEntry_8.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.windowOffsetEntry_8.setObjectName(_fromUtf8("windowOffsetEntry_8"))
        self.horizontalLayout_81.addWidget(self.windowOffsetEntry_8)
        self.verticalLayout_18.addLayout(self.horizontalLayout_81)
        self.horizontalLayout_82 = QtGui.QHBoxLayout()
        self.horizontalLayout_82.setObjectName(_fromUtf8("horizontalLayout_82"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_82.addItem(spacerItem3)
        self.numberOfTopTopologiesLabel_8 = QtGui.QLabel(self.groupBox)
        self.numberOfTopTopologiesLabel_8.setObjectName(_fromUtf8("numberOfTopTopologiesLabel_8"))
        self.horizontalLayout_82.addWidget(self.numberOfTopTopologiesLabel_8)
        self.numberOfTopTopologiesEntry_8 = QtGui.QLineEdit(self.groupBox)
        self.numberOfTopTopologiesEntry_8.setMinimumSize(QtCore.QSize(40, 21))
        self.numberOfTopTopologiesEntry_8.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.numberOfTopTopologiesEntry_8.setFont(font)
        self.numberOfTopTopologiesEntry_8.setObjectName(_fromUtf8("numberOfTopTopologiesEntry_8"))
        self.horizontalLayout_82.addWidget(self.numberOfTopTopologiesEntry_8)
        self.verticalLayout_18.addLayout(self.horizontalLayout_82)
        self.horizontalLayout_73.addLayout(self.verticalLayout_18)
        self.verticalLayout_19.addWidget(self.groupBox)
        self.toolBox.addItem(self.page, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 685, 698))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox_3 = QtGui.QGroupBox(self.page_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.checkboxAllTrees_2 = QtGui.QCheckBox(self.groupBox_3)
        self.checkboxAllTrees_2.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxAllTrees_2.setFont(font)
        self.checkboxAllTrees_2.setChecked(True)
        self.checkboxAllTrees_2.setObjectName(_fromUtf8("checkboxAllTrees_2"))
        self.horizontalLayout_24.addWidget(self.checkboxAllTrees_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.checkboxScatterPlot_2 = QtGui.QCheckBox(self.groupBox_3)
        self.checkboxScatterPlot_2.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxScatterPlot_2.setFont(font)
        self.checkboxScatterPlot_2.setChecked(True)
        self.checkboxScatterPlot_2.setObjectName(_fromUtf8("checkboxScatterPlot_2"))
        self.horizontalLayout_25.addWidget(self.checkboxScatterPlot_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.checkboxDonutPlot_2 = QtGui.QCheckBox(self.groupBox_3)
        self.checkboxDonutPlot_2.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxDonutPlot_2.setFont(font)
        self.checkboxDonutPlot_2.setChecked(True)
        self.checkboxDonutPlot_2.setObjectName(_fromUtf8("checkboxDonutPlot_2"))
        self.horizontalLayout_26.addWidget(self.checkboxDonutPlot_2)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_23.addLayout(self.verticalLayout_4)
        self.line_2 = QtGui.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_23.addWidget(self.line_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkboxStatistics_2 = QtGui.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxStatistics_2.setFont(font)
        self.checkboxStatistics_2.setChecked(False)
        self.checkboxStatistics_2.setObjectName(_fromUtf8("checkboxStatistics_2"))
        self.horizontalLayout_7.addWidget(self.checkboxStatistics_2)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.checkboxCircleGraph_2 = QtGui.QCheckBox(self.groupBox_3)
        self.checkboxCircleGraph_2.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxCircleGraph_2.setFont(font)
        self.checkboxCircleGraph_2.setChecked(True)
        self.checkboxCircleGraph_2.setObjectName(_fromUtf8("checkboxCircleGraph_2"))
        self.horizontalLayout_27.addWidget(self.checkboxCircleGraph_2)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.checkboxHeatMap_2 = QtGui.QCheckBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxHeatMap_2.setFont(font)
        self.checkboxHeatMap_2.setChecked(True)
        self.checkboxHeatMap_2.setObjectName(_fromUtf8("checkboxHeatMap_2"))
        self.horizontalLayout_28.addWidget(self.checkboxHeatMap_2)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_23.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.toolBox.addItem(self.page_2, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setEnabled(True)
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.page_3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.statisticsOptionsGroupBox = QtGui.QGroupBox(self.page_3)
        self.statisticsOptionsGroupBox.setEnabled(True)
        self.statisticsOptionsGroupBox.setAutoFillBackground(False)
        self.statisticsOptionsGroupBox.setTitle(_fromUtf8(""))
        self.statisticsOptionsGroupBox.setFlat(False)
        self.statisticsOptionsGroupBox.setCheckable(False)
        self.statisticsOptionsGroupBox.setObjectName(_fromUtf8("statisticsOptionsGroupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.statisticsOptionsGroupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.statisticsOptionsLabel = QtGui.QLabel(self.statisticsOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statisticsOptionsLabel.sizePolicy().hasHeightForWidth())
        self.statisticsOptionsLabel.setSizePolicy(sizePolicy)
        self.statisticsOptionsLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.statisticsOptionsLabel.setFont(font)
        self.statisticsOptionsLabel.setObjectName(_fromUtf8("statisticsOptionsLabel"))
        self.verticalLayout_7.addWidget(self.statisticsOptionsLabel)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.newickFileBtn = QtGui.QPushButton(self.statisticsOptionsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.newickFileBtn.setFont(font)
        self.newickFileBtn.setObjectName(_fromUtf8("newickFileBtn"))
        self.horizontalLayout_12.addWidget(self.newickFileBtn)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem10)
        self.newickFileEntry = QtGui.QLineEdit(self.statisticsOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newickFileEntry.sizePolicy().hasHeightForWidth())
        self.newickFileEntry.setSizePolicy(sizePolicy)
        self.newickFileEntry.setMinimumSize(QtCore.QSize(250, 0))
        self.newickFileEntry.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.newickFileEntry.setFont(font)
        self.newickFileEntry.setObjectName(_fromUtf8("newickFileEntry"))
        self.horizontalLayout_12.addWidget(self.newickFileEntry)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.speciesTreeNewickStringsLabel = QtGui.QLabel(self.statisticsOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speciesTreeNewickStringsLabel.sizePolicy().hasHeightForWidth())
        self.speciesTreeNewickStringsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.speciesTreeNewickStringsLabel.setFont(font)
        self.speciesTreeNewickStringsLabel.setObjectName(_fromUtf8("speciesTreeNewickStringsLabel"))
        self.horizontalLayout_11.addWidget(self.speciesTreeNewickStringsLabel)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.speciesTreeNewickStringsEntry = QtGui.QLineEdit(self.statisticsOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speciesTreeNewickStringsEntry.sizePolicy().hasHeightForWidth())
        self.speciesTreeNewickStringsEntry.setSizePolicy(sizePolicy)
        self.speciesTreeNewickStringsEntry.setMinimumSize(QtCore.QSize(250, 21))
        self.speciesTreeNewickStringsEntry.setMaximumSize(QtCore.QSize(260, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.speciesTreeNewickStringsEntry.setFont(font)
        self.speciesTreeNewickStringsEntry.setObjectName(_fromUtf8("speciesTreeNewickStringsEntry"))
        self.horizontalLayout_11.addWidget(self.speciesTreeNewickStringsEntry)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.checkboxRobinsonFoulds = QtGui.QCheckBox(self.statisticsOptionsGroupBox)
        self.checkboxRobinsonFoulds.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxRobinsonFoulds.setFont(font)
        self.checkboxRobinsonFoulds.setObjectName(_fromUtf8("checkboxRobinsonFoulds"))
        self.horizontalLayout_13.addWidget(self.checkboxRobinsonFoulds)
        self.checkboxWeighted = QtGui.QCheckBox(self.statisticsOptionsGroupBox)
        self.checkboxWeighted.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxWeighted.setFont(font)
        self.checkboxWeighted.setObjectName(_fromUtf8("checkboxWeighted"))
        self.horizontalLayout_13.addWidget(self.checkboxWeighted)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.checkboxPGTST = QtGui.QCheckBox(self.statisticsOptionsGroupBox)
        self.checkboxPGTST.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxPGTST.setFont(font)
        self.checkboxPGTST.setObjectName(_fromUtf8("checkboxPGTST"))
        self.horizontalLayout_20.addWidget(self.checkboxPGTST)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.checkboxRooted = QtGui.QCheckBox(self.statisticsOptionsGroupBox)
        self.checkboxRooted.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxRooted.setFont(font)
        self.checkboxRooted.setObjectName(_fromUtf8("checkboxRooted"))
        self.horizontalLayout_22.addWidget(self.checkboxRooted)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem12)
        self.outgroupLabel = QtGui.QLabel(self.statisticsOptionsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.outgroupLabel.setFont(font)
        self.outgroupLabel.setObjectName(_fromUtf8("outgroupLabel"))
        self.horizontalLayout_22.addWidget(self.outgroupLabel)
        self.outgroupEntry = QtGui.QLineEdit(self.statisticsOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outgroupEntry.sizePolicy().hasHeightForWidth())
        self.outgroupEntry.setSizePolicy(sizePolicy)
        self.outgroupEntry.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.outgroupEntry.setFont(font)
        self.outgroupEntry.setObjectName(_fromUtf8("outgroupEntry"))
        self.horizontalLayout_22.addWidget(self.outgroupEntry)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout.addWidget(self.statisticsOptionsGroupBox)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolBox)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.runBtn = QtGui.QPushButton(self.centralwidget)
        self.runBtn.setMinimumSize(QtCore.QSize(143, 0))
        self.runBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.runBtn.setObjectName(_fromUtf8("runBtn"))
        self.horizontalLayout_10.addWidget(self.runBtn)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_10.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_29.addWidget(self.pushButton)
        self.progressBar_2 = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.horizontalLayout_29.addWidget(self.progressBar_2)
        self.verticalLayout.addLayout(self.horizontalLayout_29)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 709, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.inputFileBtn.setText(_translate("MainWindow", "Select Input File", None))
        self.inputFileEntry.setText(_translate("MainWindow", "/Users/Peter/PycharmProjects/Evolutionary-Diversity-Visualization-Python/testFiles/phylip.txt", None))
        self.checkboxAllBootstrap.setText(_translate("MainWindow", "Bootstrap", None))
        self.label.setText(_translate("MainWindow", "Confidence Level:", None))
        self.label_2.setText(_translate("MainWindow", "Number of Bootstraps:", None))
        self.windowSizeLabel_8.setText(_translate("MainWindow", "Window Size:", None))
        self.windowSizeEntry_8.setText(_translate("MainWindow", "10", None))
        self.windowOffsetLabel_8.setText(_translate("MainWindow", "Window Offset:", None))
        self.windowOffsetEntry_8.setText(_translate("MainWindow", "10", None))
        self.numberOfTopTopologiesLabel_8.setText(_translate("MainWindow", "Number of Top Topologies:", None))
        self.numberOfTopTopologiesEntry_8.setText(_translate("MainWindow", "5", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "RAxML Options", None))
        self.checkboxAllTrees_2.setText(_translate("MainWindow", "All Trees", None))
        self.checkboxScatterPlot_2.setText(_translate("MainWindow", "Scatter Plot", None))
        self.checkboxDonutPlot_2.setText(_translate("MainWindow", "Donut Plot", None))
        self.checkboxStatistics_2.setText(_translate("MainWindow", "Statistics", None))
        self.checkboxCircleGraph_2.setText(_translate("MainWindow", "Circle Graph", None))
        self.checkboxHeatMap_2.setText(_translate("MainWindow", "Heat Map", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Graph Options", None))
        self.statisticsOptionsLabel.setText(_translate("MainWindow", "Statistics Options", None))
        self.newickFileBtn.setText(_translate("MainWindow", "Select Newick File", None))
        self.newickFileEntry.setText(_translate("MainWindow", "/Users/Peter/PycharmProjects/Evolutionary-Diversity-Visualization-Python/RAx_Files/RAxML_bestTree.0", None))
        self.speciesTreeNewickStringsLabel.setText(_translate("MainWindow", "Species Tree Newick String:", None))
        self.checkboxRobinsonFoulds.setText(_translate("MainWindow", "Robinson Foulds", None))
        self.checkboxWeighted.setText(_translate("MainWindow", "Weighted", None))
        self.checkboxPGTST.setText(_translate("MainWindow", "p(GT | ST)", None))
        self.checkboxRooted.setText(_translate("MainWindow", "rooted", None))
        self.outgroupLabel.setText(_translate("MainWindow", "Outgroup:", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Statistics Options", None))
        self.runBtn.setText(_translate("MainWindow", "Run RAxML", None))
        self.pushButton.setText(_translate("MainWindow", "Generate Graphs", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

