# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_layout.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PhylogeneticVisualization(object):
    def setupUi(self, PhylogeneticVisualization):
        PhylogeneticVisualization.setObjectName(_fromUtf8("PhylogeneticVisualization"))
        PhylogeneticVisualization.resize(777, 1001)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PhylogeneticVisualization.sizePolicy().hasHeightForWidth())
        PhylogeneticVisualization.setSizePolicy(sizePolicy)
        PhylogeneticVisualization.setMinimumSize(QtCore.QSize(459, 245))
        self.centralwidget = QtGui.QWidget(PhylogeneticVisualization)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.inputMainHorizontalLayout = QtGui.QHBoxLayout()
        self.inputMainHorizontalLayout.setObjectName(_fromUtf8("inputMainHorizontalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.welcomePage = QtGui.QWidget()
        self.welcomePage.setObjectName(_fromUtf8("welcomePage"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.welcomePage)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.welcomeLabel = QtGui.QLabel(self.welcomePage)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setObjectName(_fromUtf8("welcomeLabel"))
        self.horizontalLayout_8.addWidget(self.welcomeLabel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.modeComboBox = QtGui.QComboBox(self.welcomePage)
        self.modeComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.modeComboBox.setObjectName(_fromUtf8("modeComboBox"))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.modeComboBox)
        self.launchBtn = QtGui.QPushButton(self.welcomePage)
        self.launchBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.launchBtn.setObjectName(_fromUtf8("launchBtn"))
        self.verticalLayout_4.addWidget(self.launchBtn)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.welcomeLogoImage = QtGui.QLabel(self.welcomePage)
        self.welcomeLogoImage.setText(_fromUtf8(""))
        self.welcomeLogoImage.setObjectName(_fromUtf8("welcomeLogoImage"))
        self.horizontalLayout_4.addWidget(self.welcomeLogoImage)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.welcomePage)
        self.inputPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputPage.sizePolicy().hasHeightForWidth())
        self.inputPage.setSizePolicy(sizePolicy)
        self.inputPage.setMinimumSize(QtCore.QSize(435, 488))
        self.inputPage.setBaseSize(QtCore.QSize(0, 0))
        self.inputPage.setObjectName(_fromUtf8("inputPage"))
        self.verticalLayout = QtGui.QVBoxLayout(self.inputPage)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.inputPage)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.inputFileHL = QtGui.QHBoxLayout()
        self.inputFileHL.setObjectName(_fromUtf8("inputFileHL"))
        self.inputFileLabel = QtGui.QLabel(self.inputPage)
        self.inputFileLabel.setObjectName(_fromUtf8("inputFileLabel"))
        self.inputFileHL.addWidget(self.inputFileLabel)
        self.inputFileEntry = QtGui.QLineEdit(self.inputPage)
        self.inputFileEntry.setMinimumSize(QtCore.QSize(0, 21))
        self.inputFileEntry.setMouseTracking(True)
        self.inputFileEntry.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.inputFileEntry.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.inputFileEntry.setObjectName(_fromUtf8("inputFileEntry"))
        self.inputFileHL.addWidget(self.inputFileEntry)
        self.inputFileBtn = QtGui.QToolButton(self.inputPage)
        self.inputFileBtn.setObjectName(_fromUtf8("inputFileBtn"))
        self.inputFileHL.addWidget(self.inputFileBtn)
        self.verticalLayout.addLayout(self.inputFileHL)
        self.raxmlToolBox = QtGui.QToolBox(self.inputPage)
        self.raxmlToolBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raxmlToolBox.sizePolicy().hasHeightForWidth())
        self.raxmlToolBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.raxmlToolBox.setFont(font)
        self.raxmlToolBox.setAutoFillBackground(True)
        self.raxmlToolBox.setObjectName(_fromUtf8("raxmlToolBox"))
        self.raxmlOptionsPage = QtGui.QWidget()
        self.raxmlOptionsPage.setEnabled(True)
        self.raxmlOptionsPage.setGeometry(QtCore.QRect(0, 0, 727, 717))
        self.raxmlOptionsPage.setObjectName(_fromUtf8("raxmlOptionsPage"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.raxmlOptionsPage)
        self.verticalLayout_21.setMargin(0)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.raxmlOptionsTabWidget = QtGui.QTabWidget(self.raxmlOptionsPage)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.raxmlOptionsTabWidget.setFont(font)
        self.raxmlOptionsTabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.raxmlOptionsTabWidget.setUsesScrollButtons(False)
        self.raxmlOptionsTabWidget.setDocumentMode(False)
        self.raxmlOptionsTabWidget.setObjectName(_fromUtf8("raxmlOptionsTabWidget"))
        self.raxmlStandardOptionsTab = QtGui.QWidget()
        self.raxmlStandardOptionsTab.setObjectName(_fromUtf8("raxmlStandardOptionsTab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.raxmlStandardOptionsTab)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(5, 5, -1, 5)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.windowOptionsLabel = QtGui.QLabel(self.raxmlStandardOptionsTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.windowOptionsLabel.setFont(font)
        self.windowOptionsLabel.setIndent(-1)
        self.windowOptionsLabel.setObjectName(_fromUtf8("windowOptionsLabel"))
        self.horizontalLayout_10.addWidget(self.windowOptionsLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.windowSizeHL = QtGui.QHBoxLayout()
        self.windowSizeHL.setContentsMargins(10, 5, 5, 5)
        self.windowSizeHL.setObjectName(_fromUtf8("windowSizeHL"))
        self.windowSizeLabel = QtGui.QLabel(self.raxmlStandardOptionsTab)
        self.windowSizeLabel.setObjectName(_fromUtf8("windowSizeLabel"))
        self.windowSizeHL.addWidget(self.windowSizeLabel)
        self.windowSizeEntry = QtGui.QLineEdit(self.raxmlStandardOptionsTab)
        self.windowSizeEntry.setMinimumSize(QtCore.QSize(40, 21))
        self.windowSizeEntry.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.windowSizeEntry.setFont(font)
        self.windowSizeEntry.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.windowSizeEntry.setObjectName(_fromUtf8("windowSizeEntry"))
        self.windowSizeHL.addWidget(self.windowSizeEntry)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.windowSizeHL.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.windowSizeHL)
        self.windowOffsetHL = QtGui.QHBoxLayout()
        self.windowOffsetHL.setContentsMargins(10, 5, 5, 5)
        self.windowOffsetHL.setObjectName(_fromUtf8("windowOffsetHL"))
        self.windowOffsetLabel = QtGui.QLabel(self.raxmlStandardOptionsTab)
        self.windowOffsetLabel.setObjectName(_fromUtf8("windowOffsetLabel"))
        self.windowOffsetHL.addWidget(self.windowOffsetLabel)
        self.windowOffsetEntry = QtGui.QLineEdit(self.raxmlStandardOptionsTab)
        self.windowOffsetEntry.setMinimumSize(QtCore.QSize(40, 21))
        self.windowOffsetEntry.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.windowOffsetEntry.setFont(font)
        self.windowOffsetEntry.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.windowOffsetEntry.setObjectName(_fromUtf8("windowOffsetEntry"))
        self.windowOffsetHL.addWidget(self.windowOffsetEntry)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.windowOffsetHL.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.windowOffsetHL)
        self.numberOfTopTopologiesHL = QtGui.QHBoxLayout()
        self.numberOfTopTopologiesHL.setContentsMargins(10, 5, 5, 5)
        self.numberOfTopTopologiesHL.setObjectName(_fromUtf8("numberOfTopTopologiesHL"))
        self.numberOfTopTopologiesLabel = QtGui.QLabel(self.raxmlStandardOptionsTab)
        self.numberOfTopTopologiesLabel.setObjectName(_fromUtf8("numberOfTopTopologiesLabel"))
        self.numberOfTopTopologiesHL.addWidget(self.numberOfTopTopologiesLabel)
        self.numberOfTopTopologiesEntry = QtGui.QLineEdit(self.raxmlStandardOptionsTab)
        self.numberOfTopTopologiesEntry.setMinimumSize(QtCore.QSize(40, 21))
        self.numberOfTopTopologiesEntry.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.numberOfTopTopologiesEntry.setFont(font)
        self.numberOfTopTopologiesEntry.setObjectName(_fromUtf8("numberOfTopTopologiesEntry"))
        self.numberOfTopTopologiesHL.addWidget(self.numberOfTopTopologiesEntry)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.numberOfTopTopologiesHL.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.numberOfTopTopologiesHL)
        spacerItem9 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem9)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(5, 5, -1, 5)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.modelLabel = QtGui.QLabel(self.raxmlStandardOptionsTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.modelLabel.setFont(font)
        self.modelLabel.setObjectName(_fromUtf8("modelLabel"))
        self.horizontalLayout_16.addWidget(self.modelLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(10, 0, -1, 5)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.modelComboBox = QtGui.QComboBox(self.raxmlStandardOptionsTab)
        self.modelComboBox.setObjectName(_fromUtf8("modelComboBox"))
        self.modelComboBox.addItem(_fromUtf8(""))
        self.modelComboBox.addItem(_fromUtf8(""))
        self.modelComboBox.addItem(_fromUtf8(""))
        self.modelComboBox.addItem(_fromUtf8(""))
        self.modelComboBox.addItem(_fromUtf8(""))
        self.modelComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_18.addWidget(self.modelComboBox)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem11)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.raxmlOptionsVLine = QtGui.QFrame(self.raxmlStandardOptionsTab)
        self.raxmlOptionsVLine.setFrameShape(QtGui.QFrame.VLine)
        self.raxmlOptionsVLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.raxmlOptionsVLine.setObjectName(_fromUtf8("raxmlOptionsVLine"))
        self.horizontalLayout.addWidget(self.raxmlOptionsVLine)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setSpacing(1)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.bootstrapHL = QtGui.QHBoxLayout()
        self.bootstrapHL.setObjectName(_fromUtf8("bootstrapHL"))
        self.checkboxBootstrap = QtGui.QCheckBox(self.raxmlStandardOptionsTab)
        self.checkboxBootstrap.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkboxBootstrap.setFont(font)
        self.checkboxBootstrap.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkboxBootstrap.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkboxBootstrap.setChecked(False)
        self.checkboxBootstrap.setObjectName(_fromUtf8("checkboxBootstrap"))
        self.bootstrapHL.addWidget(self.checkboxBootstrap)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bootstrapHL.addItem(spacerItem12)
        self.verticalLayout_25.addLayout(self.bootstrapHL)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(10, -1, -1, 5)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.bootstrapGroupBox = QtGui.QGroupBox(self.raxmlStandardOptionsTab)
        self.bootstrapGroupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bootstrapGroupBox.setObjectName(_fromUtf8("bootstrapGroupBox"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.bootstrapGroupBox)
        self.verticalLayout_24.setMargin(5)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.confidenceLevelLabel = QtGui.QLabel(self.bootstrapGroupBox)
        self.confidenceLevelLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.confidenceLevelLabel.setObjectName(_fromUtf8("confidenceLevelLabel"))
        self.verticalLayout_24.addWidget(self.confidenceLevelLabel)
        self.confidenceLevelEntry = QtGui.QLineEdit(self.bootstrapGroupBox)
        self.confidenceLevelEntry.setMinimumSize(QtCore.QSize(40, 0))
        self.confidenceLevelEntry.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.confidenceLevelEntry.setFont(font)
        self.confidenceLevelEntry.setText(_fromUtf8(""))
        self.confidenceLevelEntry.setObjectName(_fromUtf8("confidenceLevelEntry"))
        self.verticalLayout_24.addWidget(self.confidenceLevelEntry)
        self.numberOfBootstrapsLabel = QtGui.QLabel(self.bootstrapGroupBox)
        self.numberOfBootstrapsLabel.setObjectName(_fromUtf8("numberOfBootstrapsLabel"))
        self.verticalLayout_24.addWidget(self.numberOfBootstrapsLabel)
        self.numberOfBootstrapsEntry = QtGui.QLineEdit(self.bootstrapGroupBox)
        self.numberOfBootstrapsEntry.setMinimumSize(QtCore.QSize(40, 0))
        self.numberOfBootstrapsEntry.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.numberOfBootstrapsEntry.setFont(font)
        self.numberOfBootstrapsEntry.setObjectName(_fromUtf8("numberOfBootstrapsEntry"))
        self.verticalLayout_24.addWidget(self.numberOfBootstrapsEntry)
        self.horizontalLayout_12.addWidget(self.bootstrapGroupBox)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem13)
        self.verticalLayout_25.addLayout(self.horizontalLayout_12)
        spacerItem14 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_25.addItem(spacerItem14)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkboxRooted = QtGui.QCheckBox(self.raxmlStandardOptionsTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkboxRooted.setFont(font)
        self.checkboxRooted.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkboxRooted.setObjectName(_fromUtf8("checkboxRooted"))
        self.horizontalLayout_7.addWidget(self.checkboxRooted)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        self.verticalLayout_25.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.outgroupGroupBox = QtGui.QGroupBox(self.raxmlStandardOptionsTab)
        self.outgroupGroupBox.setObjectName(_fromUtf8("outgroupGroupBox"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.outgroupGroupBox)
        self.horizontalLayout_11.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.outgroupLabel = QtGui.QLabel(self.outgroupGroupBox)
        self.outgroupLabel.setObjectName(_fromUtf8("outgroupLabel"))
        self.horizontalLayout_11.addWidget(self.outgroupLabel)
        self.outgroupComboBox = QtGui.QComboBox(self.outgroupGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outgroupComboBox.sizePolicy().hasHeightForWidth())
        self.outgroupComboBox.setSizePolicy(sizePolicy)
        self.outgroupComboBox.setObjectName(_fromUtf8("outgroupComboBox"))
        self.horizontalLayout_11.addWidget(self.outgroupComboBox)
        self.horizontalLayout_15.addWidget(self.outgroupGroupBox)
        self.verticalLayout_25.addLayout(self.horizontalLayout_15)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem16)
        self.horizontalLayout.addLayout(self.verticalLayout_25)
        self.raxmlOptionsTabWidget.addTab(self.raxmlStandardOptionsTab, _fromUtf8(""))
        self.raxmlAdvancedOptionsTab = QtGui.QWidget()
        self.raxmlAdvancedOptionsTab.setObjectName(_fromUtf8("raxmlAdvancedOptionsTab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.raxmlAdvancedOptionsTab)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.checkBoxCustomRaxml = QtGui.QCheckBox(self.raxmlAdvancedOptionsTab)
        self.checkBoxCustomRaxml.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBoxCustomRaxml.setFont(font)
        self.checkBoxCustomRaxml.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxCustomRaxml.setObjectName(_fromUtf8("checkBoxCustomRaxml"))
        self.horizontalLayout_9.addWidget(self.checkBoxCustomRaxml)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_4 = QtGui.QLabel(self.raxmlAdvancedOptionsTab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_21.addWidget(self.label_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.customRaxmlCommandEntry = QtGui.QLineEdit(self.raxmlAdvancedOptionsTab)
        self.customRaxmlCommandEntry.setObjectName(_fromUtf8("customRaxmlCommandEntry"))
        self.horizontalLayout_22.addWidget(self.customRaxmlCommandEntry)
        self.verticalLayout_3.addLayout(self.horizontalLayout_22)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem18)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.customRaxmlDirectoryLabel = QtGui.QLabel(self.raxmlAdvancedOptionsTab)
        self.customRaxmlDirectoryLabel.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.customRaxmlDirectoryLabel.setFont(font)
        self.customRaxmlDirectoryLabel.setObjectName(_fromUtf8("customRaxmlDirectoryLabel"))
        self.horizontalLayout_17.addWidget(self.customRaxmlDirectoryLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.customRaxmlDirectoryDescriptionLabel = QtGui.QLabel(self.raxmlAdvancedOptionsTab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.customRaxmlDirectoryDescriptionLabel.setFont(font)
        self.customRaxmlDirectoryDescriptionLabel.setObjectName(_fromUtf8("customRaxmlDirectoryDescriptionLabel"))
        self.horizontalLayout_20.addWidget(self.customRaxmlDirectoryDescriptionLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.customRaxmlDirectoryEntry = QtGui.QLineEdit(self.raxmlAdvancedOptionsTab)
        self.customRaxmlDirectoryEntry.setObjectName(_fromUtf8("customRaxmlDirectoryEntry"))
        self.horizontalLayout_6.addWidget(self.customRaxmlDirectoryEntry)
        self.customRaxmlDirectoryBtn = QtGui.QToolButton(self.raxmlAdvancedOptionsTab)
        self.customRaxmlDirectoryBtn.setObjectName(_fromUtf8("customRaxmlDirectoryBtn"))
        self.horizontalLayout_6.addWidget(self.customRaxmlDirectoryBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem19)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.generateSpeciesTreeLabel = QtGui.QLabel(self.raxmlAdvancedOptionsTab)
        self.generateSpeciesTreeLabel.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.generateSpeciesTreeLabel.setFont(font)
        self.generateSpeciesTreeLabel.setObjectName(_fromUtf8("generateSpeciesTreeLabel"))
        self.horizontalLayout_19.addWidget(self.generateSpeciesTreeLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.runRaxmlHL_2 = QtGui.QHBoxLayout()
        self.runRaxmlHL_2.setContentsMargins(5, -1, -1, -1)
        self.runRaxmlHL_2.setObjectName(_fromUtf8("runRaxmlHL_2"))
        self.generateSpeciesTreeBtn = QtGui.QPushButton(self.raxmlAdvancedOptionsTab)
        self.generateSpeciesTreeBtn.setMinimumSize(QtCore.QSize(143, 0))
        self.generateSpeciesTreeBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.generateSpeciesTreeBtn.setObjectName(_fromUtf8("generateSpeciesTreeBtn"))
        self.runRaxmlHL_2.addWidget(self.generateSpeciesTreeBtn)
        self.generateSpeciesTreeProgressBar = QtGui.QProgressBar(self.raxmlAdvancedOptionsTab)
        self.generateSpeciesTreeProgressBar.setProperty("value", 24)
        self.generateSpeciesTreeProgressBar.setInvertedAppearance(False)
        self.generateSpeciesTreeProgressBar.setObjectName(_fromUtf8("generateSpeciesTreeProgressBar"))
        self.runRaxmlHL_2.addWidget(self.generateSpeciesTreeProgressBar)
        self.verticalLayout_3.addLayout(self.runRaxmlHL_2)
        spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem20)
        self.raxmlOptionsTabWidget.addTab(self.raxmlAdvancedOptionsTab, _fromUtf8(""))
        self.verticalLayout_21.addWidget(self.raxmlOptionsTabWidget)
        self.raxmlToolBox.addItem(self.raxmlOptionsPage, _fromUtf8(""))
        self.graphOptionsPage = QtGui.QWidget()
        self.graphOptionsPage.setGeometry(QtCore.QRect(0, 0, 727, 717))
        self.graphOptionsPage.setObjectName(_fromUtf8("graphOptionsPage"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.graphOptionsPage)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.graphOptionsGroupBox = QtGui.QGroupBox(self.graphOptionsPage)
        self.graphOptionsGroupBox.setObjectName(_fromUtf8("graphOptionsGroupBox"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.graphOptionsGroupBox)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.allTreesHL = QtGui.QHBoxLayout()
        self.allTreesHL.setObjectName(_fromUtf8("allTreesHL"))
        self.checkboxAllTrees = QtGui.QCheckBox(self.graphOptionsGroupBox)
        self.checkboxAllTrees.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxAllTrees.setFont(font)
        self.checkboxAllTrees.setChecked(True)
        self.checkboxAllTrees.setObjectName(_fromUtf8("checkboxAllTrees"))
        self.allTreesHL.addWidget(self.checkboxAllTrees)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.allTreesHL.addItem(spacerItem21)
        self.verticalLayout_10.addLayout(self.allTreesHL)
        self.scatterPlotHL = QtGui.QHBoxLayout()
        self.scatterPlotHL.setObjectName(_fromUtf8("scatterPlotHL"))
        self.checkboxScatterPlot = QtGui.QCheckBox(self.graphOptionsGroupBox)
        self.checkboxScatterPlot.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxScatterPlot.setFont(font)
        self.checkboxScatterPlot.setChecked(True)
        self.checkboxScatterPlot.setObjectName(_fromUtf8("checkboxScatterPlot"))
        self.scatterPlotHL.addWidget(self.checkboxScatterPlot)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.scatterPlotHL.addItem(spacerItem22)
        self.verticalLayout_10.addLayout(self.scatterPlotHL)
        self.scatterPlotHL_2 = QtGui.QHBoxLayout()
        self.scatterPlotHL_2.setObjectName(_fromUtf8("scatterPlotHL_2"))
        self.checkboxDonutPlot = QtGui.QCheckBox(self.graphOptionsGroupBox)
        self.checkboxDonutPlot.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxDonutPlot.setFont(font)
        self.checkboxDonutPlot.setChecked(True)
        self.checkboxDonutPlot.setObjectName(_fromUtf8("checkboxDonutPlot"))
        self.scatterPlotHL_2.addWidget(self.checkboxDonutPlot)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.scatterPlotHL_2.addItem(spacerItem23)
        self.verticalLayout_10.addLayout(self.scatterPlotHL_2)
        self.horizontalLayout_30.addLayout(self.verticalLayout_10)
        self.graphOptionsVLine = QtGui.QFrame(self.graphOptionsGroupBox)
        self.graphOptionsVLine.setFrameShape(QtGui.QFrame.VLine)
        self.graphOptionsVLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.graphOptionsVLine.setObjectName(_fromUtf8("graphOptionsVLine"))
        self.horizontalLayout_30.addWidget(self.graphOptionsVLine)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.circleGraphHL = QtGui.QHBoxLayout()
        self.circleGraphHL.setObjectName(_fromUtf8("circleGraphHL"))
        self.checkboxCircleGraph = QtGui.QCheckBox(self.graphOptionsGroupBox)
        self.checkboxCircleGraph.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxCircleGraph.setFont(font)
        self.checkboxCircleGraph.setChecked(True)
        self.checkboxCircleGraph.setObjectName(_fromUtf8("checkboxCircleGraph"))
        self.circleGraphHL.addWidget(self.checkboxCircleGraph)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.circleGraphHL.addItem(spacerItem24)
        self.verticalLayout_11.addLayout(self.circleGraphHL)
        self.heatMapHL = QtGui.QHBoxLayout()
        self.heatMapHL.setObjectName(_fromUtf8("heatMapHL"))
        self.checkboxHeatMap = QtGui.QCheckBox(self.graphOptionsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxHeatMap.setFont(font)
        self.checkboxHeatMap.setChecked(True)
        self.checkboxHeatMap.setObjectName(_fromUtf8("checkboxHeatMap"))
        self.heatMapHL.addWidget(self.checkboxHeatMap)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.heatMapHL.addItem(spacerItem25)
        self.verticalLayout_11.addLayout(self.heatMapHL)
        self.statisticsHL = QtGui.QHBoxLayout()
        self.statisticsHL.setObjectName(_fromUtf8("statisticsHL"))
        self.checkboxStatistics = QtGui.QCheckBox(self.graphOptionsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxStatistics.setFont(font)
        self.checkboxStatistics.setChecked(False)
        self.checkboxStatistics.setObjectName(_fromUtf8("checkboxStatistics"))
        self.statisticsHL.addWidget(self.checkboxStatistics)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.statisticsHL.addItem(spacerItem26)
        self.verticalLayout_11.addLayout(self.statisticsHL)
        self.horizontalLayout_30.addLayout(self.verticalLayout_11)
        self.verticalLayout_9.addWidget(self.graphOptionsGroupBox)
        self.raxmlToolBox.addItem(self.graphOptionsPage, _fromUtf8(""))
        self.statisticsOptionsPage = QtGui.QWidget()
        self.statisticsOptionsPage.setEnabled(True)
        self.statisticsOptionsPage.setGeometry(QtCore.QRect(0, 0, 727, 717))
        self.statisticsOptionsPage.setObjectName(_fromUtf8("statisticsOptionsPage"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.statisticsOptionsPage)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.statisticsOptionsGroupBox = QtGui.QGroupBox(self.statisticsOptionsPage)
        self.statisticsOptionsGroupBox.setEnabled(True)
        self.statisticsOptionsGroupBox.setAutoFillBackground(False)
        self.statisticsOptionsGroupBox.setTitle(_fromUtf8(""))
        self.statisticsOptionsGroupBox.setFlat(False)
        self.statisticsOptionsGroupBox.setCheckable(False)
        self.statisticsOptionsGroupBox.setObjectName(_fromUtf8("statisticsOptionsGroupBox"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.statisticsOptionsGroupBox)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.newickFileHL = QtGui.QHBoxLayout()
        self.newickFileHL.setObjectName(_fromUtf8("newickFileHL"))
        self.label_5 = QtGui.QLabel(self.statisticsOptionsGroupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.newickFileHL.addWidget(self.label_5)
        self.newickFileEntry = QtGui.QLineEdit(self.statisticsOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newickFileEntry.sizePolicy().hasHeightForWidth())
        self.newickFileEntry.setSizePolicy(sizePolicy)
        self.newickFileEntry.setMinimumSize(QtCore.QSize(250, 0))
        self.newickFileEntry.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.newickFileEntry.setFont(font)
        self.newickFileEntry.setObjectName(_fromUtf8("newickFileEntry"))
        self.newickFileHL.addWidget(self.newickFileEntry)
        self.newickFileBtn = QtGui.QToolButton(self.statisticsOptionsGroupBox)
        self.newickFileBtn.setObjectName(_fromUtf8("newickFileBtn"))
        self.newickFileHL.addWidget(self.newickFileBtn)
        self.verticalLayout_12.addLayout(self.newickFileHL)
        self.newickStringHL = QtGui.QHBoxLayout()
        self.newickStringHL.setObjectName(_fromUtf8("newickStringHL"))
        self.speciesTreeNewickStringsLabel = QtGui.QLabel(self.statisticsOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speciesTreeNewickStringsLabel.sizePolicy().hasHeightForWidth())
        self.speciesTreeNewickStringsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.speciesTreeNewickStringsLabel.setFont(font)
        self.speciesTreeNewickStringsLabel.setObjectName(_fromUtf8("speciesTreeNewickStringsLabel"))
        self.newickStringHL.addWidget(self.speciesTreeNewickStringsLabel)
        self.speciesTreeNewickStringsEntry = QtGui.QLineEdit(self.statisticsOptionsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speciesTreeNewickStringsEntry.sizePolicy().hasHeightForWidth())
        self.speciesTreeNewickStringsEntry.setSizePolicy(sizePolicy)
        self.speciesTreeNewickStringsEntry.setMinimumSize(QtCore.QSize(250, 21))
        self.speciesTreeNewickStringsEntry.setMaximumSize(QtCore.QSize(16777215, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.speciesTreeNewickStringsEntry.setFont(font)
        self.speciesTreeNewickStringsEntry.setText(_fromUtf8(""))
        self.speciesTreeNewickStringsEntry.setObjectName(_fromUtf8("speciesTreeNewickStringsEntry"))
        self.newickStringHL.addWidget(self.speciesTreeNewickStringsEntry)
        self.verticalLayout_12.addLayout(self.newickStringHL)
        self.label_6 = QtGui.QLabel(self.statisticsOptionsGroupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_12.addWidget(self.label_6)
        self.robinsonFouldsHL = QtGui.QHBoxLayout()
        self.robinsonFouldsHL.setObjectName(_fromUtf8("robinsonFouldsHL"))
        self.checkboxRobinsonFoulds = QtGui.QCheckBox(self.statisticsOptionsGroupBox)
        self.checkboxRobinsonFoulds.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxRobinsonFoulds.setFont(font)
        self.checkboxRobinsonFoulds.setObjectName(_fromUtf8("checkboxRobinsonFoulds"))
        self.robinsonFouldsHL.addWidget(self.checkboxRobinsonFoulds)
        self.checkboxWeighted = QtGui.QCheckBox(self.statisticsOptionsGroupBox)
        self.checkboxWeighted.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxWeighted.setFont(font)
        self.checkboxWeighted.setObjectName(_fromUtf8("checkboxWeighted"))
        self.robinsonFouldsHL.addWidget(self.checkboxWeighted)
        self.verticalLayout_12.addLayout(self.robinsonFouldsHL)
        self.pgtstHL = QtGui.QHBoxLayout()
        self.pgtstHL.setObjectName(_fromUtf8("pgtstHL"))
        self.checkboxPGTST = QtGui.QCheckBox(self.statisticsOptionsGroupBox)
        self.checkboxPGTST.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkboxPGTST.setFont(font)
        self.checkboxPGTST.setObjectName(_fromUtf8("checkboxPGTST"))
        self.pgtstHL.addWidget(self.checkboxPGTST)
        self.verticalLayout_12.addLayout(self.pgtstHL)
        spacerItem27 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem27)
        self.horizontalLayout_5.addWidget(self.statisticsOptionsGroupBox)
        self.raxmlToolBox.addItem(self.statisticsOptionsPage, _fromUtf8(""))
        self.verticalLayout.addWidget(self.raxmlToolBox)
        self.line = QtGui.QFrame(self.inputPage)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.runRaxmlHL = QtGui.QHBoxLayout()
        self.runRaxmlHL.setObjectName(_fromUtf8("runRaxmlHL"))
        self.runBtn = QtGui.QPushButton(self.inputPage)
        self.runBtn.setMinimumSize(QtCore.QSize(143, 0))
        self.runBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.runBtn.setObjectName(_fromUtf8("runBtn"))
        self.runRaxmlHL.addWidget(self.runBtn)
        self.progressBar = QtGui.QProgressBar(self.inputPage)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.runRaxmlHL.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.runRaxmlHL)
        self.stackedWidget.addWidget(self.inputPage)
        self.fileConverterPage = QtGui.QWidget()
        self.fileConverterPage.setObjectName(_fromUtf8("fileConverterPage"))
        self.gridLayout_2 = QtGui.QGridLayout(self.fileConverterPage)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.fileConverterPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.inputFormatLabel = QtGui.QLabel(self.fileConverterPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.inputFormatLabel.setFont(font)
        self.inputFormatLabel.setObjectName(_fromUtf8("inputFormatLabel"))
        self.gridLayout_2.addWidget(self.inputFormatLabel, 3, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.fileConverterPage)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 5, 0, 1, 1)
        self.outputFormatDescriptionLabel = QtGui.QLabel(self.fileConverterPage)
        font = QtGui.QFont()
        font.setItalic(True)
        self.outputFormatDescriptionLabel.setFont(font)
        self.outputFormatDescriptionLabel.setObjectName(_fromUtf8("outputFormatDescriptionLabel"))
        self.gridLayout_2.addWidget(self.outputFormatDescriptionLabel, 7, 0, 1, 1)
        spacerItem28 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem28, 8, 0, 1, 1)
        self.runFileConverterBtn = QtGui.QPushButton(self.fileConverterPage)
        self.runFileConverterBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.runFileConverterBtn.setObjectName(_fromUtf8("runFileConverterBtn"))
        self.gridLayout_2.addWidget(self.runFileConverterBtn, 9, 0, 1, 1)
        self.outputFormatLabel = QtGui.QLabel(self.fileConverterPage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.outputFormatLabel.setFont(font)
        self.outputFormatLabel.setObjectName(_fromUtf8("outputFormatLabel"))
        self.gridLayout_2.addWidget(self.outputFormatLabel, 6, 0, 1, 1)
        self.inputFormatComboBox = QtGui.QComboBox(self.fileConverterPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputFormatComboBox.sizePolicy().hasHeightForWidth())
        self.inputFormatComboBox.setSizePolicy(sizePolicy)
        self.inputFormatComboBox.setObjectName(_fromUtf8("inputFormatComboBox"))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.inputFormatComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.inputFormatComboBox, 4, 0, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.fileConverterBtn = QtGui.QPushButton(self.fileConverterPage)
        self.fileConverterBtn.setObjectName(_fromUtf8("fileConverterBtn"))
        self.horizontalLayout_23.addWidget(self.fileConverterBtn)
        self.fileConverterEntry = QtGui.QLineEdit(self.fileConverterPage)
        self.fileConverterEntry.setObjectName(_fromUtf8("fileConverterEntry"))
        self.horizontalLayout_23.addWidget(self.fileConverterEntry)
        self.gridLayout_2.addLayout(self.horizontalLayout_23, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.fileConverterPage)
        self.msComparisonPage = QtGui.QWidget()
        self.msComparisonPage.setObjectName(_fromUtf8("msComparisonPage"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.msComparisonPage)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.msFileHL = QtGui.QHBoxLayout()
        self.msFileHL.setObjectName(_fromUtf8("msFileHL"))
        self.msFileLabel = QtGui.QLabel(self.msComparisonPage)
        self.msFileLabel.setObjectName(_fromUtf8("msFileLabel"))
        self.msFileHL.addWidget(self.msFileLabel)
        self.msFileEntry = QtGui.QLineEdit(self.msComparisonPage)
        self.msFileEntry.setMinimumSize(QtCore.QSize(0, 21))
        self.msFileEntry.setMouseTracking(True)
        self.msFileEntry.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.msFileEntry.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.msFileEntry.setObjectName(_fromUtf8("msFileEntry"))
        self.msFileHL.addWidget(self.msFileEntry)
        self.msFileBtn = QtGui.QToolButton(self.msComparisonPage)
        self.msFileBtn.setObjectName(_fromUtf8("msFileBtn"))
        self.msFileHL.addWidget(self.msFileBtn)
        self.verticalLayout_5.addLayout(self.msFileHL)
        self.groupBox = QtGui.QGroupBox(self.msComparisonPage)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.msRaxmlDirectoryLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.msRaxmlDirectoryLabel.setFont(font)
        self.msRaxmlDirectoryLabel.setObjectName(_fromUtf8("msRaxmlDirectoryLabel"))
        self.verticalLayout_6.addWidget(self.msRaxmlDirectoryLabel)
        self.msRaxmlDirectoryDescriptionLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.msRaxmlDirectoryDescriptionLabel.setFont(font)
        self.msRaxmlDirectoryDescriptionLabel.setObjectName(_fromUtf8("msRaxmlDirectoryDescriptionLabel"))
        self.verticalLayout_6.addWidget(self.msRaxmlDirectoryDescriptionLabel)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.msRaxmlDirectoryEntry = QtGui.QLineEdit(self.groupBox)
        self.msRaxmlDirectoryEntry.setObjectName(_fromUtf8("msRaxmlDirectoryEntry"))
        self.horizontalLayout_13.addWidget(self.msRaxmlDirectoryEntry)
        self.msRaxmlDirectoryBtn = QtGui.QToolButton(self.groupBox)
        self.msRaxmlDirectoryBtn.setObjectName(_fromUtf8("msRaxmlDirectoryBtn"))
        self.horizontalLayout_13.addWidget(self.msRaxmlDirectoryBtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.windowLabel = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.windowLabel.setFont(font)
        self.windowLabel.setIndent(-1)
        self.windowLabel.setObjectName(_fromUtf8("windowLabel"))
        self.verticalLayout_6.addWidget(self.windowLabel)
        self.msWindowSizeHL = QtGui.QHBoxLayout()
        self.msWindowSizeHL.setObjectName(_fromUtf8("msWindowSizeHL"))
        self.msWindowSizeLabel = QtGui.QLabel(self.groupBox)
        self.msWindowSizeLabel.setObjectName(_fromUtf8("msWindowSizeLabel"))
        self.msWindowSizeHL.addWidget(self.msWindowSizeLabel)
        self.msWindowSizeEntry = QtGui.QLineEdit(self.groupBox)
        self.msWindowSizeEntry.setMinimumSize(QtCore.QSize(40, 21))
        self.msWindowSizeEntry.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.msWindowSizeEntry.setFont(font)
        self.msWindowSizeEntry.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.msWindowSizeEntry.setObjectName(_fromUtf8("msWindowSizeEntry"))
        self.msWindowSizeHL.addWidget(self.msWindowSizeEntry)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.msWindowSizeHL.addItem(spacerItem29)
        self.verticalLayout_6.addLayout(self.msWindowSizeHL)
        self.msWindowOffsetHL = QtGui.QHBoxLayout()
        self.msWindowOffsetHL.setObjectName(_fromUtf8("msWindowOffsetHL"))
        self.msWindowOffsetLabel = QtGui.QLabel(self.groupBox)
        self.msWindowOffsetLabel.setObjectName(_fromUtf8("msWindowOffsetLabel"))
        self.msWindowOffsetHL.addWidget(self.msWindowOffsetLabel)
        self.msWindowOffsetEntry = QtGui.QLineEdit(self.groupBox)
        self.msWindowOffsetEntry.setMinimumSize(QtCore.QSize(40, 21))
        self.msWindowOffsetEntry.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.msWindowOffsetEntry.setFont(font)
        self.msWindowOffsetEntry.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.msWindowOffsetEntry.setObjectName(_fromUtf8("msWindowOffsetEntry"))
        self.msWindowOffsetHL.addWidget(self.msWindowOffsetEntry)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.msWindowOffsetHL.addItem(spacerItem30)
        self.verticalLayout_6.addLayout(self.msWindowOffsetHL)
        self.windowLabel.raise_()
        self.msRaxmlDirectoryLabel.raise_()
        self.msRaxmlDirectoryDescriptionLabel.raise_()
        self.verticalLayout_5.addWidget(self.groupBox)
        spacerItem31 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem31)
        self.msCompareBtn = QtGui.QPushButton(self.msComparisonPage)
        self.msCompareBtn.setObjectName(_fromUtf8("msCompareBtn"))
        self.verticalLayout_5.addWidget(self.msCompareBtn)
        self.stackedWidget.addWidget(self.msComparisonPage)
        self.dStatisticPage = QtGui.QWidget()
        self.dStatisticPage.setObjectName(_fromUtf8("dStatisticPage"))
        self.theD = QtGui.QLabel(self.dStatisticPage)
        self.theD.setGeometry(QtCore.QRect(180, 70, 391, 16))
        self.theD.setObjectName(_fromUtf8("theD"))
        self.stackedWidget.addWidget(self.dStatisticPage)
        self.outputPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputPage.sizePolicy().hasHeightForWidth())
        self.outputPage.setSizePolicy(sizePolicy)
        self.outputPage.setObjectName(_fromUtf8("outputPage"))
        self.gridLayout_5 = QtGui.QGridLayout(self.outputPage)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.stackedWidget.addWidget(self.outputPage)
        self.inputMainHorizontalLayout.addWidget(self.stackedWidget)
        self.gridLayout.addLayout(self.inputMainHorizontalLayout, 0, 0, 1, 1)
        PhylogeneticVisualization.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PhylogeneticVisualization)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExport = QtGui.QMenu(self.menuFile)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuMode = QtGui.QMenu(self.menubar)
        self.menuMode.setObjectName(_fromUtf8("menuMode"))
        self.menuDisplay = QtGui.QMenu(self.menubar)
        self.menuDisplay.setObjectName(_fromUtf8("menuDisplay"))
        PhylogeneticVisualization.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(PhylogeneticVisualization)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionRax = QtGui.QAction(PhylogeneticVisualization)
        self.actionRax.setCheckable(True)
        self.actionRax.setChecked(False)
        self.actionRax.setObjectName(_fromUtf8("actionRax"))
        self.actionConverter = QtGui.QAction(PhylogeneticVisualization)
        self.actionConverter.setCheckable(True)
        self.actionConverter.setObjectName(_fromUtf8("actionConverter"))
        self.actionMS = QtGui.QAction(PhylogeneticVisualization)
        self.actionMS.setCheckable(True)
        self.actionMS.setObjectName(_fromUtf8("actionMS"))
        self.actionDStatistic = QtGui.QAction(PhylogeneticVisualization)
        self.actionDStatistic.setCheckable(True)
        self.actionDStatistic.setObjectName(_fromUtf8("actionDStatistic"))
        self.actionStandardJPG = QtGui.QAction(PhylogeneticVisualization)
        self.actionStandardJPG.setObjectName(_fromUtf8("actionStandardJPG"))
        self.actionBootstrapJPG = QtGui.QAction(PhylogeneticVisualization)
        self.actionBootstrapJPG.setObjectName(_fromUtf8("actionBootstrapJPG"))
        self.actionTextFile = QtGui.QAction(PhylogeneticVisualization)
        self.actionTextFile.setObjectName(_fromUtf8("actionTextFile"))
        self.actionWindowsDirectory = QtGui.QAction(PhylogeneticVisualization)
        self.actionWindowsDirectory.setObjectName(_fromUtf8("actionWindowsDirectory"))
        self.actionRAXDirectory = QtGui.QAction(PhylogeneticVisualization)
        self.actionRAXDirectory.setObjectName(_fromUtf8("actionRAXDirectory"))
        self.actionTreesDirectory = QtGui.QAction(PhylogeneticVisualization)
        self.actionTreesDirectory.setObjectName(_fromUtf8("actionTreesDirectory"))
        self.actionAllTrees = QtGui.QAction(PhylogeneticVisualization)
        self.actionAllTrees.setCheckable(True)
        self.actionAllTrees.setObjectName(_fromUtf8("actionAllTrees"))
        self.actionScatterPlot = QtGui.QAction(PhylogeneticVisualization)
        self.actionScatterPlot.setCheckable(True)
        self.actionScatterPlot.setObjectName(_fromUtf8("actionScatterPlot"))
        self.actionDonutPlot = QtGui.QAction(PhylogeneticVisualization)
        self.actionDonutPlot.setCheckable(True)
        self.actionDonutPlot.setObjectName(_fromUtf8("actionDonutPlot"))
        self.actionCircleGraph = QtGui.QAction(PhylogeneticVisualization)
        self.actionCircleGraph.setCheckable(True)
        self.actionCircleGraph.setObjectName(_fromUtf8("actionCircleGraph"))
        self.actionStatistics = QtGui.QAction(PhylogeneticVisualization)
        self.actionStatistics.setObjectName(_fromUtf8("actionStatistics"))
        self.menuExport.addAction(self.actionStandardJPG)
        self.menuExport.addAction(self.actionBootstrapJPG)
        self.menuExport.addAction(self.actionTextFile)
        self.menuExport.addSeparator()
        self.menuExport.addAction(self.actionWindowsDirectory)
        self.menuExport.addAction(self.actionRAXDirectory)
        self.menuExport.addAction(self.actionTreesDirectory)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuMode.addAction(self.actionRax)
        self.menuMode.addAction(self.actionConverter)
        self.menuMode.addAction(self.actionMS)
        self.menuMode.addAction(self.actionDStatistic)
        self.menuDisplay.addAction(self.actionAllTrees)
        self.menuDisplay.addAction(self.actionScatterPlot)
        self.menuDisplay.addAction(self.actionDonutPlot)
        self.menuDisplay.addAction(self.actionCircleGraph)
        self.menuDisplay.addAction(self.actionStatistics)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())

        self.retranslateUi(PhylogeneticVisualization)
        self.stackedWidget.setCurrentIndex(1)
        self.raxmlToolBox.setCurrentIndex(0)
        self.raxmlOptionsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PhylogeneticVisualization)

    def retranslateUi(self, PhylogeneticVisualization):
        PhylogeneticVisualization.setWindowTitle(_translate("PhylogeneticVisualization", "Phylogenetic Visualization", None))
        self.welcomeLabel.setText(_translate("PhylogeneticVisualization", "Welcome Daddy", None))
        self.modeComboBox.setItemText(0, _translate("PhylogeneticVisualization", "RAx_ML", None))
        self.modeComboBox.setItemText(1, _translate("PhylogeneticVisualization", "File Converter", None))
        self.modeComboBox.setItemText(2, _translate("PhylogeneticVisualization", "MS Comparison", None))
        self.modeComboBox.setItemText(3, _translate("PhylogeneticVisualization", "D Statistic", None))
        self.modeComboBox.setItemText(4, _translate("PhylogeneticVisualization", "Tetris", None))
        self.modeComboBox.setItemText(5, _translate("PhylogeneticVisualization", "Snake", None))
        self.launchBtn.setText(_translate("PhylogeneticVisualization", "Launch", None))
        self.label_2.setText(_translate("PhylogeneticVisualization", "Select Alignment", None))
        self.inputFileLabel.setText(_translate("PhylogeneticVisualization", "Alignment:", None))
        self.inputFileEntry.setText(_translate("PhylogeneticVisualization", "/Users/Peter/PycharmProjects/Evolutionary-Diversity-Visualization-Python/testFiles/phylip.txt", None))
        self.inputFileBtn.setText(_translate("PhylogeneticVisualization", "...", None))
        self.windowOptionsLabel.setText(_translate("PhylogeneticVisualization", "Window", None))
        self.windowSizeLabel.setText(_translate("PhylogeneticVisualization", "Window Size:", None))
        self.windowSizeEntry.setText(_translate("PhylogeneticVisualization", "10", None))
        self.windowOffsetLabel.setText(_translate("PhylogeneticVisualization", "Window Offset:", None))
        self.windowOffsetEntry.setText(_translate("PhylogeneticVisualization", "10", None))
        self.numberOfTopTopologiesLabel.setText(_translate("PhylogeneticVisualization", "Number of Top Topologies:", None))
        self.numberOfTopTopologiesEntry.setText(_translate("PhylogeneticVisualization", "5", None))
        self.modelLabel.setText(_translate("PhylogeneticVisualization", "Model", None))
        self.modelComboBox.setItemText(0, _translate("PhylogeneticVisualization", "GTRGAMMA", None))
        self.modelComboBox.setItemText(1, _translate("PhylogeneticVisualization", "GTRCAT", None))
        self.modelComboBox.setItemText(2, _translate("PhylogeneticVisualization", "GTRCATI", None))
        self.modelComboBox.setItemText(3, _translate("PhylogeneticVisualization", "ASC_GTRCAT", None))
        self.modelComboBox.setItemText(4, _translate("PhylogeneticVisualization", "ASC_GTRGAMMA", None))
        self.modelComboBox.setItemText(5, _translate("PhylogeneticVisualization", "GTRGAMMAI", None))
        self.checkboxBootstrap.setText(_translate("PhylogeneticVisualization", "Bootstrap", None))
        self.confidenceLevelLabel.setText(_translate("PhylogeneticVisualization", "Confidence Level", None))
        self.numberOfBootstrapsLabel.setText(_translate("PhylogeneticVisualization", "Number of Bootstraps", None))
        self.checkboxRooted.setText(_translate("PhylogeneticVisualization", "Rooted", None))
        self.outgroupLabel.setText(_translate("PhylogeneticVisualization", "Outgroup:", None))
        self.raxmlOptionsTabWidget.setTabText(self.raxmlOptionsTabWidget.indexOf(self.raxmlStandardOptionsTab), _translate("PhylogeneticVisualization", "Standard", None))
        self.checkBoxCustomRaxml.setText(_translate("PhylogeneticVisualization", "Custom RAxML Command", None))
        self.label_4.setText(_translate("PhylogeneticVisualization", "The -s and -n flags will be handled internally.", None))
        self.customRaxmlDirectoryLabel.setText(_translate("PhylogeneticVisualization", "Custom RAxML Directory", None))
        self.customRaxmlDirectoryDescriptionLabel.setText(_translate("PhylogeneticVisualization", "If you have already run RAxML select the alignment directory below.", None))
        self.customRaxmlDirectoryBtn.setText(_translate("PhylogeneticVisualization", "...", None))
        self.generateSpeciesTreeLabel.setText(_translate("PhylogeneticVisualization", "Generate Species Tree", None))
        self.generateSpeciesTreeBtn.setText(_translate("PhylogeneticVisualization", "Generate Species Tree", None))
        self.raxmlOptionsTabWidget.setTabText(self.raxmlOptionsTabWidget.indexOf(self.raxmlAdvancedOptionsTab), _translate("PhylogeneticVisualization", "Advanced", None))
        self.raxmlToolBox.setItemText(self.raxmlToolBox.indexOf(self.raxmlOptionsPage), _translate("PhylogeneticVisualization", "RAxML Options", None))
        self.checkboxAllTrees.setText(_translate("PhylogeneticVisualization", "All Trees", None))
        self.checkboxScatterPlot.setText(_translate("PhylogeneticVisualization", "Scatter Plot", None))
        self.checkboxDonutPlot.setText(_translate("PhylogeneticVisualization", "Donut Plot", None))
        self.checkboxCircleGraph.setText(_translate("PhylogeneticVisualization", "Circle Graph", None))
        self.checkboxHeatMap.setText(_translate("PhylogeneticVisualization", "Heat Map", None))
        self.checkboxStatistics.setText(_translate("PhylogeneticVisualization", "Statistics", None))
        self.raxmlToolBox.setItemText(self.raxmlToolBox.indexOf(self.graphOptionsPage), _translate("PhylogeneticVisualization", "Graph Options", None))
        self.label_5.setText(_translate("PhylogeneticVisualization", "Species Tree File:", None))
        self.newickFileEntry.setText(_translate("PhylogeneticVisualization", "/Users/Peter/PycharmProjects/Evolutionary-Diversity-Visualization-Python/RAx_Files/RAxML_bestTree.0", None))
        self.newickFileBtn.setText(_translate("PhylogeneticVisualization", "...", None))
        self.speciesTreeNewickStringsLabel.setText(_translate("PhylogeneticVisualization", "Species Tree Newick:", None))
        self.label_6.setText(_translate("PhylogeneticVisualization", "Plots:", None))
        self.checkboxRobinsonFoulds.setText(_translate("PhylogeneticVisualization", "Robinson Foulds", None))
        self.checkboxWeighted.setText(_translate("PhylogeneticVisualization", "Weighted", None))
        self.checkboxPGTST.setText(_translate("PhylogeneticVisualization", "p(GT | ST)", None))
        self.raxmlToolBox.setItemText(self.raxmlToolBox.indexOf(self.statisticsOptionsPage), _translate("PhylogeneticVisualization", "Statistics Options", None))
        self.runBtn.setText(_translate("PhylogeneticVisualization", "Run RAxML", None))
        self.label.setText(_translate("PhylogeneticVisualization", "Input File", None))
        self.inputFormatLabel.setText(_translate("PhylogeneticVisualization", "Input Format:", None))
        self.outputFormatDescriptionLabel.setText(_translate("PhylogeneticVisualization", "This is a relaxed interpretation of the PHYLIP format which allows\n"
" long names.", None))
        self.runFileConverterBtn.setText(_translate("PhylogeneticVisualization", "Convert", None))
        self.outputFormatLabel.setText(_translate("PhylogeneticVisualization", "Output Format:", None))
        self.inputFormatComboBox.setItemText(0, _translate("PhylogeneticVisualization", "CLUSTAL", None))
        self.inputFormatComboBox.setItemText(1, _translate("PhylogeneticVisualization", "EMBOSS", None))
        self.inputFormatComboBox.setItemText(2, _translate("PhylogeneticVisualization", "FASTA", None))
        self.inputFormatComboBox.setItemText(3, _translate("PhylogeneticVisualization", "FASTA-m10", None))
        self.inputFormatComboBox.setItemText(4, _translate("PhylogeneticVisualization", "IG", None))
        self.inputFormatComboBox.setItemText(5, _translate("PhylogeneticVisualization", "MAF", None))
        self.inputFormatComboBox.setItemText(6, _translate("PhylogeneticVisualization", "Mauve", None))
        self.inputFormatComboBox.setItemText(7, _translate("PhylogeneticVisualization", "NEXUS", None))
        self.inputFormatComboBox.setItemText(8, _translate("PhylogeneticVisualization", "PHYLIP", None))
        self.inputFormatComboBox.setItemText(9, _translate("PhylogeneticVisualization", "PHYLIP-sequential", None))
        self.inputFormatComboBox.setItemText(10, _translate("PhylogeneticVisualization", "Stockholm", None))
        self.fileConverterBtn.setText(_translate("PhylogeneticVisualization", "Choose File", None))
        self.msFileLabel.setText(_translate("PhylogeneticVisualization", "MS File:", None))
        self.msFileEntry.setText(_translate("PhylogeneticVisualization", "/Users/Peter/PycharmProjects/Evolutionary-Diversity-Visualization-Python/testFiles/fakeMS.txt", None))
        self.msFileBtn.setText(_translate("PhylogeneticVisualization", "...", None))
        self.msRaxmlDirectoryLabel.setText(_translate("PhylogeneticVisualization", "RAxML Directory", None))
        self.msRaxmlDirectoryDescriptionLabel.setText(_translate("PhylogeneticVisualization", "Choose directory containing RAxML files.", None))
        self.msRaxmlDirectoryEntry.setText(_translate("PhylogeneticVisualization", "/Users/Peter/PycharmProjects/Evolutionary-Diversity-Visualization-Python/RAxML_Files", None))
        self.msRaxmlDirectoryBtn.setText(_translate("PhylogeneticVisualization", "...", None))
        self.windowLabel.setText(_translate("PhylogeneticVisualization", "Window", None))
        self.msWindowSizeLabel.setText(_translate("PhylogeneticVisualization", "Window Size:", None))
        self.msWindowSizeEntry.setText(_translate("PhylogeneticVisualization", "10", None))
        self.msWindowOffsetLabel.setText(_translate("PhylogeneticVisualization", "Window Offset:", None))
        self.msWindowOffsetEntry.setText(_translate("PhylogeneticVisualization", "10", None))
        self.msCompareBtn.setText(_translate("PhylogeneticVisualization", "Compare", None))
        self.theD.setText(_translate("PhylogeneticVisualization", "the D -- coming soon ~ ft. travis benedict ;)", None))
        self.menuFile.setTitle(_translate("PhylogeneticVisualization", "File", None))
        self.menuExport.setTitle(_translate("PhylogeneticVisualization", "Export...", None))
        self.menuMode.setTitle(_translate("PhylogeneticVisualization", "Mode", None))
        self.menuDisplay.setTitle(_translate("PhylogeneticVisualization", "Display", None))
        self.actionOpen.setText(_translate("PhylogeneticVisualization", "Open...", None))
        self.actionOpen.setShortcut(_translate("PhylogeneticVisualization", "Ctrl+O", None))
        self.actionRax.setText(_translate("PhylogeneticVisualization", "RAx_ML", None))
        self.actionConverter.setText(_translate("PhylogeneticVisualization", "Converter", None))
        self.actionMS.setText(_translate("PhylogeneticVisualization", "MS", None))
        self.actionDStatistic.setText(_translate("PhylogeneticVisualization", "D Statistic", None))
        self.actionStandardJPG.setText(_translate("PhylogeneticVisualization", "Standard JPG", None))
        self.actionBootstrapJPG.setText(_translate("PhylogeneticVisualization", "Bootstrap JPG ", None))
        self.actionTextFile.setText(_translate("PhylogeneticVisualization", "Text File", None))
        self.actionWindowsDirectory.setText(_translate("PhylogeneticVisualization", "Windows Directory", None))
        self.actionRAXDirectory.setText(_translate("PhylogeneticVisualization", "RAX Directory", None))
        self.actionTreesDirectory.setText(_translate("PhylogeneticVisualization", "Trees Directory", None))
        self.actionAllTrees.setText(_translate("PhylogeneticVisualization", "All Trees", None))
        self.actionScatterPlot.setText(_translate("PhylogeneticVisualization", "Scatter Plot", None))
        self.actionDonutPlot.setText(_translate("PhylogeneticVisualization", "Donut Plot", None))
        self.actionCircleGraph.setText(_translate("PhylogeneticVisualization", "Circle Graph", None))
        self.actionStatistics.setText(_translate("PhylogeneticVisualization", "Statistics", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    PhylogeneticVisualization = QtGui.QMainWindow()
    ui = Ui_PhylogeneticVisualization()
    ui.setupUi(PhylogeneticVisualization)
    PhylogeneticVisualization.show()
    sys.exit(app.exec_())

